package main

// dissent_canonical.go — Wave 12 D8, the first Dissent port: src/crypto.ts
// from the Dissent repo, byte-for-byte. Every receipt and self-authenticating
// planId in Dissent depends on this canonicalization, so the Go port is pinned
// by cross-language golden vectors (testdata/dissent_canonical_golden.json,
// generated by running the REAL TypeScript over the fixtures; regenerate or
// audit with testdata/dissent-golden.mjs, which records the sha256 of the
// crypto.ts it ran).
//
// The TS reference:
//
//	canonicalJson(value): primitives via JSON.stringify; arrays element-wise;
//	objects with entries sorted by JS string comparison (UTF-16 code units),
//	keys JSON.stringify'd, no whitespace; undefined anywhere throws.
//	sha256(value): hex digest of the UTF-8 bytes.
//	hmacSha256(secret, value): base64url (no padding) HMAC-SHA256 digest.
//
// Divergences from Go's encoding/json that this file special-cases so the
// bytes match JSON.stringify: no HTML escaping (<, >, & stay raw), U+2028 /
// U+2029 stay raw, control characters use lowercase \u00xx, numbers follow
// ECMAScript Number::toString (shortest round-trip digits, exponent form at
// >= 1e21 and < 1e-6 as "1e+21" / "1e-7", -0 prints as 0), and object keys
// sort by UTF-16 code units — NOT Go's byte order, which would put astral
// characters (surrogate pairs) after U+E000..U+FFFF instead of before.
//
// Lone surrogates are the one place a JS string has no Go equivalent: JS
// strings are UTF-16 and may hold an unpaired D800..DFFF code unit, which
// well-formed JSON.stringify re-emits as a \udXXX escape. Go carries such a
// string as WTF-8 (ED A0 80 …), which dissentWriteJSONString re-escapes the
// same way — but Go's encoding/json REPLACES a \ud800 escape with U+FFFD
// while JSON.parse keeps it, so the same JSON text would otherwise hash
// differently on the two sides. dissentDecodeJSON is the fail-closed entry
// point for JSON TEXT: it refuses unpaired surrogate escapes rather than let
// encoding/json silently change the digest.

import (
	"crypto/hmac"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"
	"unicode/utf16"
	"unicode/utf8"
)

// dissentCanonicalJSON renders value exactly as Dissent's canonicalJson.
// Accepted shapes are the JSON-decoded ones: nil, bool, float64 (and the
// other Go numeric kinds), string, []any, map[string]any — plus json.Number
// via its string form. Anything else is an error (the TS throws on
// undefined; Go has no undefined, so unsupported types take that slot).
func dissentCanonicalJSON(value any) (string, error) {
	var builder strings.Builder
	if err := dissentCanonicalWrite(&builder, value); err != nil {
		return "", err
	}
	return builder.String(), nil
}

func dissentCanonicalWrite(builder *strings.Builder, value any) error {
	switch typed := value.(type) {
	case nil:
		builder.WriteString("null")
	case bool:
		if typed {
			builder.WriteString("true")
		} else {
			builder.WriteString("false")
		}
	case string:
		return dissentWriteJSONString(builder, typed)
	case float64:
		builder.WriteString(dissentFormatNumber(typed))
	case float32:
		builder.WriteString(dissentFormatNumber(float64(typed)))
	case int:
		builder.WriteString(dissentFormatNumber(float64(typed)))
	case int64:
		builder.WriteString(dissentFormatNumber(float64(typed)))
	case int32:
		builder.WriteString(dissentFormatNumber(float64(typed)))
	case uint:
		builder.WriteString(dissentFormatNumber(float64(typed)))
	case uint64:
		builder.WriteString(dissentFormatNumber(float64(typed)))
	case interface{ Float64() (float64, error) }: // json.Number
		parsed, err := typed.Float64()
		if err != nil {
			return fmt.Errorf("canonical JSON number: %w", err)
		}
		builder.WriteString(dissentFormatNumber(parsed))
	case []any:
		builder.WriteByte('[')
		for index, item := range typed {
			if index > 0 {
				builder.WriteByte(',')
			}
			if err := dissentCanonicalWrite(builder, item); err != nil {
				return err
			}
		}
		builder.WriteByte(']')
	case map[string]any:
		keys := make([]string, 0, len(typed))
		for key := range typed {
			keys = append(keys, key)
		}
		// Sort by UTF-16 code unit, then — so the order never depends on Go's
		// randomized map iteration — by the raw Go string, which is a total
		// order on distinct keys.
		sort.Slice(keys, func(i, j int) bool {
			if order := dissentCompareUTF16(keys[i], keys[j]); order != 0 {
				return order < 0
			}
			return keys[i] < keys[j]
		})
		// Two DIFFERENT Go strings can be the SAME JavaScript string: a WTF-8
		// surrogate pair (ED A0 BD ED B8 80) and the astral rune it stands for
		// (F0 9F 98 80) are one JS string, "😀". A JS object holds
		// one property per string, so a Go map carrying both describes an
		// object the TypeScript could never have built, and every ordering of
		// it emits a duplicate key that no canonicalJson output can match.
		// Refuse it rather than mint a contractSha256 / planId the other side
		// cannot verify — the same fail-closed stance dissentDecodeJSON and
		// dissentWriteJSONString take. The tie-break above makes the pair
		// reported here deterministic.
		for index := 1; index < len(keys); index++ {
			if dissentCompareUTF16(keys[index-1], keys[index]) == 0 {
				return fmt.Errorf("canonical JSON object: keys % x and % x are the same JavaScript string (identical UTF-16 code units), which no JavaScript object could hold twice", keys[index-1], keys[index])
			}
		}
		builder.WriteByte('{')
		for index, key := range keys {
			if index > 0 {
				builder.WriteByte(',')
			}
			if err := dissentWriteJSONString(builder, key); err != nil {
				return err
			}
			builder.WriteByte(':')
			if err := dissentCanonicalWrite(builder, typed[key]); err != nil {
				return err
			}
		}
		builder.WriteByte('}')
	default:
		return fmt.Errorf("value of type %T is not canonical JSON", value)
	}
	return nil
}

// dissentUTF16Step reads the UTF-16 code unit(s) the JS string equivalent of
// value starts with, walking the bytes exactly as dissentWriteJSONString
// does: utf8.DecodeRuneInString, and on an invalid byte a WTF-8 lone
// surrogate. It returns the units, how many of them there are (1 or 2) and
// how many bytes were consumed.
//
// Going through []rune instead is the trap this exists to close: Go's decoder
// turns each of the three WTF-8 bytes of a lone surrogate into U+FFFD, so
// "\xed\xa0\x80" and "\xed\xbf\xbf" — two DIFFERENT JS strings, which the
// writer now renders as \ud800 and \udfff — collapse to the same
// [FFFD FFFD FFFD] and compare EQUAL, leaving the object-key sort at the
// mercy of Go's randomized map iteration and hashing one value two ways.
func dissentUTF16Step(value string) (high uint16, low uint16, units int, size int) {
	char, width := utf8.DecodeRuneInString(value)
	if char == utf8.RuneError && width == 1 {
		if unit, ok := dissentDecodeWTF8Surrogate(value); ok {
			return uint16(unit), 0, 1, 3
		}
		// Not UTF-8 and not WTF-8: no JS counterpart at all. Go's own decoder
		// calls it U+FFFD, and dissentWriteJSONString refuses it outright
		// before any digest is taken, so nothing downstream can hash it.
		return uint16(utf8.RuneError), 0, 1, 1
	}
	if char > 0xFFFF {
		encodedHigh, encodedLow := utf16.EncodeRune(char)
		return uint16(encodedHigh), uint16(encodedLow), 2, width
	}
	return uint16(char), 0, 1, width
}

// dissentUTF16Units is the string as a JS engine holds it: a sequence of
// UTF-16 code units. A WTF-8 surrogate pair and the astral rune it stands for
// yield the same two units, as they are the same JS string.
func dissentUTF16Units(value string) []uint16 {
	units := make([]uint16, 0, len(value))
	for index := 0; index < len(value); {
		high, low, count, size := dissentUTF16Step(value[index:])
		units = append(units, high)
		if count == 2 {
			units = append(units, low)
		}
		index += size
	}
	return units
}

// dissentUTF16Length is JavaScript's String.length, without allocating.
func dissentUTF16Length(value string) int {
	length := 0
	for index := 0; index < len(value); {
		_, _, count, size := dissentUTF16Step(value[index:])
		length += count
		index += size
	}
	return length
}

// dissentCompareUTF16 orders two strings the way JavaScript's < does: by
// UTF-16 code unit, so "😀" (D83D DE00) sorts before "￿" and a lone \ud800
// key sorts before both.
func dissentCompareUTF16(a, b string) int {
	left := dissentUTF16Units(a)
	right := dissentUTF16Units(b)
	for index := 0; index < len(left) && index < len(right); index++ {
		if left[index] != right[index] {
			if left[index] < right[index] {
				return -1
			}
			return 1
		}
	}
	switch {
	case len(left) < len(right):
		return -1
	case len(left) > len(right):
		return 1
	}
	return 0
}

const dissentHexDigits = "0123456789abcdef"

// dissentWriteJSONString is JSON.stringify for strings: only ", \ and
// control characters below 0x20 are escaped (short forms for \b \f \n \r
// \t, lowercase \u00xx otherwise); everything else — including <, >, &,
// U+2028, U+2029 and U+007F — is written raw as UTF-8. A lone surrogate,
// which Go carries as its 3-byte WTF-8 encoding (ED A0 80 … ED BF BF), is
// written as the lowercase \udXXX escape that well-formed JSON.stringify
// emits for the same UTF-16 code unit. Any OTHER invalid UTF-8 has no JS
// counterpart at all (JS strings are sequences of UTF-16 code units), so it
// is refused rather than silently canonicalized to some other digest.
func dissentWriteJSONString(builder *strings.Builder, value string) error {
	builder.WriteByte('"')
	for index := 0; index < len(value); {
		char, size := utf8.DecodeRuneInString(value[index:])
		if char == utf8.RuneError && size == 1 {
			if unit, ok := dissentDecodeWTF8Surrogate(value[index:]); ok {
				// A high surrogate immediately followed by a low one is ONE
				// astral character to a JS string, and JSON.stringify writes
				// it raw; only a genuinely unpaired unit gets the escape.
				if low, paired := dissentDecodeWTF8Surrogate(value[index+3:]); unit <= 0xDBFF && paired && low >= 0xDC00 {
					builder.WriteRune(utf16.DecodeRune(unit, low))
					index += 6
					continue
				}
				dissentWriteUnicodeEscape(builder, unit)
				index += 3
				continue
			}
			return fmt.Errorf("canonical JSON string: byte 0x%02x at offset %d is not valid UTF-8 or WTF-8", value[index], index)
		}
		switch char {
		case '"':
			builder.WriteString(`\"`)
		case '\\':
			builder.WriteString(`\\`)
		case '\b':
			builder.WriteString(`\b`)
		case '\f':
			builder.WriteString(`\f`)
		case '\n':
			builder.WriteString(`\n`)
		case '\r':
			builder.WriteString(`\r`)
		case '\t':
			builder.WriteString(`\t`)
		default:
			if char < 0x20 {
				dissentWriteUnicodeEscape(builder, char)
			} else {
				builder.WriteString(value[index : index+size])
			}
		}
		index += size
	}
	builder.WriteByte('"')
	return nil
}

// dissentWriteUnicodeEscape writes a JSON.stringify UnicodeEscape: \u plus
// four LOWERCASE hex digits.
func dissentWriteUnicodeEscape(builder *strings.Builder, unit rune) {
	builder.WriteString(`\u`)
	builder.WriteByte(dissentHexDigits[(unit>>12)&0xf])
	builder.WriteByte(dissentHexDigits[(unit>>8)&0xf])
	builder.WriteByte(dissentHexDigits[(unit>>4)&0xf])
	builder.WriteByte(dissentHexDigits[unit&0xf])
}

// dissentDecodeWTF8Surrogate reads the 3-byte WTF-8 encoding of a lone
// surrogate (U+D800..U+DFFF), which Go's utf8 decoder rejects, and returns
// the UTF-16 code unit it stands for.
func dissentDecodeWTF8Surrogate(value string) (rune, bool) {
	if len(value) < 3 || value[0] != 0xED || value[1] < 0xA0 || value[1] > 0xBF || value[2] < 0x80 || value[2] > 0xBF {
		return 0, false
	}
	return rune(value[0]&0x0f)<<12 | rune(value[1]&0x3f)<<6 | rune(value[2]&0x3f), true
}

// dissentDecodeJSON is the JSON.parse-faithful entry point for JSON TEXT.
// Go's encoding/json replaces an unpaired \uD800..\uDFFF escape with U+FFFD
// while JSON.parse keeps the code unit, so decoding such a document with
// encoding/json and canonicalizing the result yields a DIFFERENT
// contractSha256 / planId than the TypeScript for byte-identical input. The
// port refuses those documents instead of minting a receipt that the other
// side cannot verify.
func dissentDecodeJSON(text string) (any, error) {
	var value any
	if err := json.Unmarshal([]byte(text), &value); err != nil {
		return nil, err
	}
	if err := dissentRejectLoneSurrogateEscapes(text); err != nil {
		return nil, err
	}
	return value, nil
}

// dissentRejectLoneSurrogateEscapes scans validated JSON text for an
// unpaired \uD800..\uDFFF escape. Backslashes only occur inside strings in
// well-formed JSON, and escape pairs are consumed two characters at a time,
// so a flat scan cannot mistake a literal `\\u0041` for an escape.
func dissentRejectLoneSurrogateEscapes(text string) error {
	readUnit := func(index int) (rune, bool) {
		if index+6 > len(text) || text[index] != '\\' || text[index+1] != 'u' {
			return 0, false
		}
		unit, err := strconv.ParseUint(text[index+2:index+6], 16, 32)
		if err != nil {
			return 0, false
		}
		return rune(unit), true
	}
	for index := 0; index < len(text); {
		if text[index] != '\\' {
			index++
			continue
		}
		unit, ok := readUnit(index)
		if !ok {
			index += 2 // \" \\ \/ \b \f \n \r \t — never the start of an escape
			continue
		}
		if unit >= 0xD800 && unit <= 0xDBFF {
			if low, ok := readUnit(index + 6); ok && low >= 0xDC00 && low <= 0xDFFF {
				index += 12
				continue
			}
		}
		if unit >= 0xD800 && unit <= 0xDFFF {
			return fmt.Errorf("JSON text at offset %d carries an unpaired surrogate escape \\u%04x, which Go and JavaScript decode differently", index, unit)
		}
		index += 6
	}
	return nil
}

// dissentFormatNumber is ECMAScript Number::toString for a finite double
// (JSON.stringify prints NaN/±Infinity as null). Shortest round-trip digits,
// plain decimal for exponents in [-7, 21), otherwise d.ddde±x.
func dissentFormatNumber(value float64) string {
	if math.IsNaN(value) || math.IsInf(value, 0) {
		return "null"
	}
	if value == 0 {
		return "0"
	}
	sign := ""
	if value < 0 {
		sign = "-"
		value = -value
	}
	// Shortest digits that round-trip, in d.ddd…e±xx form.
	scientific := strconv.FormatFloat(value, 'e', -1, 64)
	mantissa, exponentText, _ := strings.Cut(scientific, "e")
	exponent, _ := strconv.Atoi(exponentText)
	digits := strings.Replace(mantissa, ".", "", 1)
	// n is the decimal exponent such that value = 0.digits × 10^n
	// (ECMAScript's k digits and n).
	n := exponent + 1
	k := len(digits)
	switch {
	case k <= n && n <= 21:
		return sign + digits + strings.Repeat("0", n-k)
	case 0 < n && n <= 21:
		return sign + digits[:n] + "." + digits[n:]
	case -6 < n && n <= 0:
		return sign + "0." + strings.Repeat("0", -n) + digits
	}
	exponentSign := "+"
	if n-1 < 0 {
		exponentSign = "-"
	}
	exponentDigits := strconv.Itoa(int(math.Abs(float64(n - 1))))
	if k == 1 {
		return sign + digits + "e" + exponentSign + exponentDigits
	}
	return sign + digits[:1] + "." + digits[1:] + "e" + exponentSign + exponentDigits
}

// dissentSha256Hex is Dissent's sha256(): the hex digest of the UTF-8 bytes.
func dissentSha256Hex(value string) string {
	sum := sha256.Sum256([]byte(value))
	return hex.EncodeToString(sum[:])
}

// dissentHMACSha256Base64URL is Dissent's hmacSha256(secret, value): the
// HMAC-SHA256 digest as unpadded base64url (43 characters).
func dissentHMACSha256Base64URL(secret string, value string) string {
	mac := hmac.New(sha256.New, []byte(secret))
	mac.Write([]byte(value))
	return base64.RawURLEncoding.EncodeToString(mac.Sum(nil))
}

// dissentVerifyHMAC recomputes the digest and compares it to expected in
// constant time (the TS verifyApiKey shape: length check + timingSafeEqual).
func dissentVerifyHMAC(secret string, value string, expected string) bool {
	actual := dissentHMACSha256Base64URL(secret, value)
	if len(actual) != len(expected) {
		return false
	}
	return subtle.ConstantTimeCompare([]byte(actual), []byte(expected)) == 1
}
