package main

// dissent_plan.go — Wave 12 D8, second Dissent port: src/coordination.ts (the
// dissent.work.v1 work contract, the executor/assurance qualification
// registries, the coordination runtime authority, compileIntelligencePlan,
// executionProfileId, sealPlan / parseIntelligencePlan) and src/assurance.ts
// (work-class classifier + risk escalation). Pure and deterministic: no I/O,
// no wiring into any product path. Pinned byte-for-byte by
// testdata/dissent_plan_golden.json (generated by the real TypeScript over
// TEST-ONLY registries; regenerate or audit with testdata/dissent-plan-golden.mjs,
// which records the sha256 of every source it ran).
//
// Inputs are JSON-decoded values (map[string]any / []any / float64 / string /
// bool / nil) so the validation mirrors zod exactly: strict objects (unknown
// keys refuse), enums, ranges, nullable fields, and the contract's defaults
// (risk, humanReviewRequired, assurance, quality, metadata, consequences),
// which are applied BEFORE contractSha256 is taken — exactly as the TS parse
// output is what gets hashed. Registries and the tenant policy carry no
// defaults, so their hashes are taken over the validated input as-is.
//
// EVERY refusal carries a code (dissentPlanError.Code): contract_invalid,
// registry_invalid, runtime_invalid, plan_invalid, plan_identity_mismatch —
// including the ones raised past the parsers, where a canonicalization fails
// on bytes reader.str never checked. Callers switch on that code, so a bare
// error is a hole, not a smaller bug; the code names the INPUT that owns the
// value (the assurance registry is a runtime-authority field, so its digest
// failures are runtime_invalid). The TS throws zod errors without codes; the
// plan STATUSES
// (clarification_required / policy_blocked / qualification_required / ready)
// are the fail-closed gates and are reproduced verbatim. routing.ts's
// INSUFFICIENT_PROVIDER_COVERAGE belongs to the (not yet ported) provider
// router, not to this kernel; the constant is declared here so the code
// vocabulary is in one place.
//
// The exact-set work-class match (a route must be qualified for EXACTLY the
// detected classes) is kept as in TS; the STRIDE superset relaxation comes
// later behind an option.

import (
	"encoding/json"
	"fmt"
	"math"
	"regexp"
	"sort"
	"strings"
)

// ---------------------------------------------------------------------------
// ECMAScript semantics the Go standard library does not share
// ---------------------------------------------------------------------------

// dissentMaxSafeInteger is Number.MAX_SAFE_INTEGER. zod's .int() accepts any
// Number.isInteger value (up to ~1.8e308), which Go's int cannot hold: the
// float64 -> int conversion of, say, 2^63 is implementation-defined and the
// assurance critical-path sum of three such seats WRAPS to a small positive
// number that slips under the deadline gate the TypeScript fails closed on.
// Every integer this kernel reads is therefore refused above the range where
// a JS number is still an exact integer — which is also the range where the
// TypeScript itself has already fail-closed (the contract deadline ceiling is
// 3_600_000 ms, so no larger timeout can ever be selected or fit a critical
// path), and it keeps the three-seat sum far below int64 overflow.
const dissentMaxSafeInteger = float64(1<<53 - 1)

// dissentJSWhitespace is JavaScript's \s as an RE2 character class. Go's \s
// is only [\t\n\f\r ]; ECMAScript's is WhiteSpace + LineTerminator, i.e. every
// Unicode space separator plus \v, NBSP, U+2028/9 and the BOM. A corpus pasted
// from Word, Google Docs or HTML routinely separates words with U+00A0, and
// with Go's \s the consequence detector silently misses it.
const dissentJSWhitespace = `[\t\n\v\f\r \x{00a0}\x{1680}\x{2000}-\x{200a}\x{2028}\x{2029}\x{202f}\x{205f}\x{3000}\x{feff}]`

// dissentStringLength is JavaScript's String.length — UTF-16 code units, the
// unit every zod .min()/.max() on a string measures. Counting runes instead
// lets an astral-character payload be accepted by one implementation and
// rejected by the other (150k emoji is 300k code units, over context's 200k
// cap; "😀😀" is 4 units, over objective's 3-unit floor).
//
// It shares dissentUTF16Length's walk with the canonicalizer's key
// comparator, so a lone surrogate counts as the ONE code unit JS sees. A
// `for _, char := range value` loop instead makes Go's decoder mangle each of
// the three WTF-8 bytes into a separate U+FFFD and count 3.
func dissentStringLength(value string) int {
	return dissentUTF16Length(value)
}

// dissentToLowerJS is String.prototype.toLowerCase. Go's strings.ToLower is
// the SIMPLE lowercase mapping; ECMAScript applies the FULL locale-insensitive
// mapping, which additionally expands U+0130 (LATIN CAPITAL LETTER I WITH DOT
// ABOVE) to "i" + U+0307 COMBINING DOT ABOVE. That combining mark breaks the
// ASCII word boundaries the classifier patterns rely on, so "PRODUCTİON"
// matches the production signal in Go and does not in JS.
//
// The only other locale-insensitive special case is Final_Sigma (Σ lowercases
// to ς, not σ, at the end of a word). It cannot change any outcome here:
// every classifier pattern is pure ASCII and RE2's \b, like a non-unicode
// JS \b, treats σ and ς alike as non-word characters.
func dissentToLowerJS(value string) string {
	if !strings.ContainsRune(value, '\u0130') {
		return strings.ToLower(value)
	}
	return strings.ToLower(strings.ReplaceAll(value, "\u0130", "\u0069\u0307"))
}

const (
	dissentWorkContractVersion     = "dissent.work.v1"
	dissentIntelligencePlanVersion = "dissent.intelligence-plan.v1"

	dissentErrContractInvalid      = "contract_invalid"
	dissentErrRegistryInvalid      = "registry_invalid"
	dissentErrRuntimeInvalid       = "runtime_invalid"
	dissentErrPlanInvalid          = "plan_invalid"
	dissentErrPlanIdentityMismatch = "plan_identity_mismatch"
	// dissentErrInsufficientProviderCoverage is routing.ts's code (two
	// independent qualified frontier families are required); declared for the
	// shared vocabulary, raised by the router port, not by this kernel.
	dissentErrInsufficientProviderCoverage = "INSUFFICIENT_PROVIDER_COVERAGE"

	dissentStatusReady                 = "ready"
	dissentStatusClarificationRequired = "clarification_required"
	dissentStatusQualificationRequired = "qualification_required"
	dissentStatusPolicyBlocked         = "policy_blocked"

	dissentTopologyDirect      = "direct"
	dissentTopologyFullDissent = "full_dissent"
)

var (
	dissentProviders        = []string{"openai", "anthropic", "xai"}
	dissentReasoningEfforts = []string{"low", "medium", "high", "max"}
	dissentRiskLevels       = []string{"standard", "high", "critical"}
	// dissentWorkClasses is workClassSchema.options — the registry key order.
	dissentWorkClasses = []string{
		"software_security", "software_reliability", "software_correctness", "research_factuality",
		"business_decision", "document_contract", "general",
	}
	// dissentWorkClassPriority is assurance.ts's PRIORITY — the output order.
	dissentWorkClassPriority = []string{
		"software_security", "software_reliability", "software_correctness", "research_factuality",
		"document_contract", "business_decision", "general",
	}
	dissentQualities      = []string{"efficient", "balanced", "best"}
	dissentOutputFormats  = []string{"text", "json", "code", "document"}
	dissentClassification = []string{"public", "internal", "confidential"}
	dissentArtifactKinds  = []string{"code_diff", "document", "decision", "analysis", "other"}
	// dissentConsequenceNames is the consequenceFactsSchema shape order — the
	// order Object.entries walks in classifyAssurance / consequentialUnknowns.
	dissentConsequenceNames = []string{"production", "customerData", "moneyMovement", "irreversible", "regulated"}

	dissentSha256Pattern             = regexp.MustCompile(`^[a-f0-9]{64}$`)
	dissentAssuranceProfileIDPattern = regexp.MustCompile(`^(?:dp_)?[a-f0-9]{64}$`)
)

// dissentPlanError is a validation failure with the code vocabulary above.
type dissentPlanError struct {
	Code    string
	Message string
}

func (err *dissentPlanError) Error() string { return err.Code + ": " + err.Message }

func dissentFail(code string, format string, args ...any) error {
	return &dissentPlanError{Code: code, Message: fmt.Sprintf(format, args...)}
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type dissentConsequenceFacts struct {
	Production    *bool
	CustomerData  *bool
	MoneyMovement *bool
	Irreversible  *bool
	Regulated     *bool
}

func (facts dissentConsequenceFacts) get(name string) *bool {
	switch name {
	case "production":
		return facts.Production
	case "customerData":
		return facts.CustomerData
	case "moneyMovement":
		return facts.MoneyMovement
	case "irreversible":
		return facts.Irreversible
	case "regulated":
		return facts.Regulated
	}
	return nil
}

func (facts *dissentConsequenceFacts) set(name string, value *bool) {
	switch name {
	case "production":
		facts.Production = value
	case "customerData":
		facts.CustomerData = value
	case "moneyMovement":
		facts.MoneyMovement = value
	case "irreversible":
		facts.Irreversible = value
	case "regulated":
		facts.Regulated = value
	}
}

func (facts dissentConsequenceFacts) isTrue(name string) bool {
	value := facts.get(name)
	return value != nil && *value
}

func (facts dissentConsequenceFacts) canonical() map[string]any {
	out := map[string]any{}
	for _, name := range dissentConsequenceNames {
		if value := facts.get(name); value == nil {
			out[name] = nil
		} else {
			out[name] = *value
		}
	}
	return out
}

type dissentWorkContract struct {
	Version             string
	Objective           string
	Context             string
	AcceptanceCriteria  []string
	OutputFormat        string
	OutputInstructions  string
	Risk                string
	Consequences        dissentConsequenceFacts
	Reversible          *bool
	HumanReviewRequired bool
	Assurance           string
	Quality             string
	Modality            string
	Interaction         string
	Tools               string
	SideEffects         string
	DataClassification  string
	ProviderStorage     string
	ContextRetention    string
	EndToEndDeadlineMs  int
	Metadata            map[string]string
}

// canonical is the zod parse output shape (defaults applied) — what
// contractSha256 hashes.
func (contract dissentWorkContract) canonical() map[string]any {
	criteria := make([]any, 0, len(contract.AcceptanceCriteria))
	for _, item := range contract.AcceptanceCriteria {
		criteria = append(criteria, item)
	}
	metadata := map[string]any{}
	for key, value := range contract.Metadata {
		metadata[key] = value
	}
	var reversible any
	if contract.Reversible != nil {
		reversible = *contract.Reversible
	}
	return map[string]any{
		"version":             contract.Version,
		"objective":           contract.Objective,
		"context":             contract.Context,
		"acceptanceCriteria":  criteria,
		"output":              map[string]any{"format": contract.OutputFormat, "instructions": contract.OutputInstructions},
		"risk":                contract.Risk,
		"consequences":        contract.Consequences.canonical(),
		"reversible":          reversible,
		"humanReviewRequired": contract.HumanReviewRequired,
		"assurance":           contract.Assurance,
		"quality":             contract.Quality,
		"modality":            contract.Modality,
		"interaction":         contract.Interaction,
		"tools":               contract.Tools,
		"sideEffects":         contract.SideEffects,
		"dataPolicy":          map[string]any{"classification": contract.DataClassification, "providerStorage": contract.ProviderStorage, "contextRetention": contract.ContextRetention},
		"latency":             map[string]any{"endToEndDeadlineMs": float64(contract.EndToEndDeadlineMs)},
		"metadata":            metadata,
	}
}

type dissentExecutionProfile struct {
	Provider        string `json:"provider"`
	Model           string `json:"model"`
	ReasoningEffort string `json:"reasoningEffort"`
	TimeoutMs       int    `json:"timeoutMs"`
	MaxOutputTokens int    `json:"maxOutputTokens"`
}

func (profile dissentExecutionProfile) canonical() map[string]any {
	return map[string]any{
		"provider": profile.Provider, "model": profile.Model, "reasoningEffort": profile.ReasoningEffort,
		"timeoutMs": float64(profile.TimeoutMs), "maxOutputTokens": float64(profile.MaxOutputTokens),
	}
}

type dissentExecutorRoute struct {
	Profile                   dissentExecutionProfile
	ProfileID                 string
	QualifiedWorkClasses      []string
	EligibleQualities         []string
	QualificationReportSha256 string
}

type dissentExecutorRegistry struct {
	Version            string
	ProductionEligible bool
	SourceReportSha256 *string
	Routes             map[string][]dissentExecutorRoute
	raw                any // the validated input, hashed as registrySha256
}

type dissentAssuranceSeat struct {
	Profile                   dissentExecutionProfile
	ProfileID                 string
	QualificationReportSha256 string
}

type dissentAssuranceCoverage struct {
	Reviewer   []dissentAssuranceSeat
	Challenger []dissentAssuranceSeat
	Judge      []dissentAssuranceSeat
}

type dissentAssuranceRegistry struct {
	Version            string
	ProductionEligible bool
	SourceReportSha256 *string
	Coverage           map[string]dissentAssuranceCoverage
	raw                any
}

type dissentTenantPolicy struct {
	Version          string
	Authenticated    bool
	SourceSha256     *string
	AllowedProviders []string
	raw              any
}

type dissentRuntimeAuthority struct {
	TenantPolicy       dissentTenantPolicy
	AvailableProviders []string
	AssuranceRegistry  dissentAssuranceRegistry
}

// dissentCheckInput is DissentCheckInput as the classifier reads it.
type dissentCheckInput struct {
	Objective          string
	ArtifactKind       string
	ArtifactContent    string
	AcceptanceCriteria []string
	Risk               string
	Consequences       dissentConsequenceFacts
	Metadata           map[string]string
}

type dissentAssuranceClassification struct {
	RequestedRisk string   `json:"requestedRisk"`
	EffectiveRisk string   `json:"effectiveRisk"`
	WorkClasses   []string `json:"workClasses"`
	Reasons       []string `json:"reasons"`
}

// Plan (wire shape = intelligencePlanSchema; json tags are the TS keys).
type dissentPlanSeat struct {
	Provider                  string `json:"provider"`
	Model                     string `json:"model"`
	ReasoningEffort           string `json:"reasoningEffort"`
	TimeoutMs                 int    `json:"timeoutMs"`
	MaxOutputTokens           int    `json:"maxOutputTokens"`
	ProfileID                 string `json:"profileId"`
	QualificationReportSha256 string `json:"qualificationReportSha256"`
}

type dissentAssuranceAssignment struct {
	WorkClass  string          `json:"workClass"`
	Reviewer   dissentPlanSeat `json:"reviewer"`
	Challenger dissentPlanSeat `json:"challenger"`
	Judge      dissentPlanSeat `json:"judge"`
}

type dissentPlanAssurance struct {
	Required                    bool                         `json:"required"`
	ExcludedMakerProvider       *string                      `json:"excludedMakerProvider"`
	RequiredIndependentFamilies int                          `json:"requiredIndependentFamilies"`
	HumanGateAfterAssurance     bool                         `json:"humanGateAfterAssurance"`
	RegistryVersion             *string                      `json:"registryVersion"`
	SourceReportSha256          *string                      `json:"sourceReportSha256"`
	RegistrySha256              *string                      `json:"registrySha256"`
	Assignments                 []dissentAssuranceAssignment `json:"assignments"`
}

type dissentLatencyBudget struct {
	EndToEndDeadlineMs             int  `json:"endToEndDeadlineMs"`
	ExecutorTimeoutMs              *int `json:"executorTimeoutMs"`
	AssuranceCriticalPathTimeoutMs int  `json:"assuranceCriticalPathTimeoutMs"`
	WorstCaseTimeoutMs             *int `json:"worstCaseTimeoutMs"`
}

type dissentPlanRegistryRef struct {
	Version            string  `json:"version"`
	SourceReportSha256 *string `json:"sourceReportSha256"`
	RegistrySha256     string  `json:"registrySha256"`
}

type dissentPlanPolicyRef struct {
	Version      string  `json:"version"`
	SourceSha256 *string `json:"sourceSha256"`
	PolicySha256 string  `json:"policySha256"`
}

type dissentHostBoundary struct {
	Tools       string `json:"tools"`
	SideEffects string `json:"sideEffects"`
	Memory      string `json:"memory"`
	Approval    string `json:"approval"`
}

type dissentIntelligencePlan struct {
	Version                     string                 `json:"version"`
	ID                          string                 `json:"id"`
	Status                      string                 `json:"status"`
	ContractSha256              string                 `json:"contractSha256"`
	ExecutorRegistry            dissentPlanRegistryRef `json:"executorRegistry"`
	TenantPolicy                dissentPlanPolicyRef   `json:"tenantPolicy"`
	AvailabilitySha256          string                 `json:"availabilitySha256"`
	QualificationAuthorityClass string                 `json:"qualificationAuthorityClass"`
	WorkClasses                 []string               `json:"workClasses"`
	Topology                    *string                `json:"topology"`
	Executor                    *dissentPlanSeat       `json:"executor"`
	Assurance                   dissentPlanAssurance   `json:"assurance"`
	LatencyBudget               dissentLatencyBudget   `json:"latencyBudget"`
	Reasons                     []string               `json:"reasons"`
	Clarification               []string               `json:"clarification"`
	HostBoundary                dissentHostBoundary    `json:"hostBoundary"`
	ContinuityMode              string                 `json:"continuityMode"`
}

// dissentPlanCanonical renders a plan through the canonical encoder (the
// bytes the TS canonicalJson(plan) produces). Nil slices print as [] because
// every slice field is initialised non-nil by the compiler and the parser.
func dissentPlanCanonical(plan dissentIntelligencePlan) (string, error) {
	generic, err := dissentToGeneric(plan)
	if err != nil {
		return "", err
	}
	return dissentCanonicalJSON(generic)
}

func dissentToGeneric(value any) (any, error) {
	raw, err := json.Marshal(value)
	if err != nil {
		return nil, err
	}
	var generic any
	if err := json.Unmarshal(raw, &generic); err != nil {
		return nil, err
	}
	return generic, nil
}

// ---------------------------------------------------------------------------
// zod-shaped readers over decoded JSON
// ---------------------------------------------------------------------------

type dissentReader struct {
	code string
}

func (reader dissentReader) object(value any, path string, allowed ...string) (map[string]any, error) {
	object, ok := value.(map[string]any)
	if !ok || value == nil {
		return nil, dissentFail(reader.code, "%s must be an object", path)
	}
	if allowed != nil {
		permitted := map[string]bool{}
		for _, key := range allowed {
			permitted[key] = true
		}
		for key := range object {
			if !permitted[key] {
				return nil, dissentFail(reader.code, "%s: unrecognized key %q", path, key)
			}
		}
	}
	return object, nil
}

func (reader dissentReader) str(object map[string]any, key string, path string, min int, max int) (string, error) {
	raw, present := object[key]
	if !present {
		return "", dissentFail(reader.code, "%s.%s is required", path, key)
	}
	value, ok := raw.(string)
	if !ok {
		return "", dissentFail(reader.code, "%s.%s must be a string", path, key)
	}
	length := dissentStringLength(value)
	if length < min || (max > 0 && length > max) {
		return "", dissentFail(reader.code, "%s.%s length %d is outside [%d,%d]", path, key, length, min, max)
	}
	return value, nil
}

func (reader dissentReader) literal(object map[string]any, key string, path string, want string) (string, error) {
	value, err := reader.str(object, key, path, 0, 0)
	if err != nil {
		return "", err
	}
	if value != want {
		return "", dissentFail(reader.code, "%s.%s must be %q", path, key, want)
	}
	return value, nil
}

func (reader dissentReader) enum(object map[string]any, key string, path string, options []string, fallback string) (string, error) {
	raw, present := object[key]
	if !present {
		if fallback != "" {
			return fallback, nil
		}
		return "", dissentFail(reader.code, "%s.%s is required", path, key)
	}
	value, ok := raw.(string)
	if !ok || !dissentContains(options, value) {
		return "", dissentFail(reader.code, "%s.%s must be one of %v", path, key, options)
	}
	return value, nil
}

func (reader dissentReader) boolean(object map[string]any, key string, path string, fallback *bool) (bool, error) {
	raw, present := object[key]
	if !present {
		if fallback != nil {
			return *fallback, nil
		}
		return false, dissentFail(reader.code, "%s.%s is required", path, key)
	}
	value, ok := raw.(bool)
	if !ok {
		return false, dissentFail(reader.code, "%s.%s must be a boolean", path, key)
	}
	return value, nil
}

func (reader dissentReader) nullableBool(object map[string]any, key string, path string, required bool) (*bool, error) {
	raw, present := object[key]
	if !present || raw == nil {
		if required && !present {
			return nil, dissentFail(reader.code, "%s.%s is required", path, key)
		}
		return nil, nil
	}
	value, ok := raw.(bool)
	if !ok {
		return nil, dissentFail(reader.code, "%s.%s must be a boolean or null", path, key)
	}
	return &value, nil
}

func (reader dissentReader) integer(object map[string]any, key string, path string, min float64, max float64) (int, error) {
	raw, present := object[key]
	if !present {
		return 0, dissentFail(reader.code, "%s.%s is required", path, key)
	}
	value, ok := raw.(float64)
	if !ok || value != math.Trunc(value) || math.IsInf(value, 0) {
		return 0, dissentFail(reader.code, "%s.%s must be an integer", path, key)
	}
	if value < min || value > max {
		return 0, dissentFail(reader.code, "%s.%s %v is outside [%v,%v]", path, key, value, min, max)
	}
	// zod's .int() has no ceiling; Go's int does. Refuse anything the
	// float64 -> int conversion cannot carry exactly (see
	// dissentMaxSafeInteger) rather than wrap a crafted timeout into a small
	// positive number that passes the deadline gate.
	if value > dissentMaxSafeInteger || value < -dissentMaxSafeInteger {
		return 0, dissentFail(reader.code, "%s.%s %v is outside the exactly-representable integer range", path, key, value)
	}
	return int(value), nil
}

func (reader dissentReader) nullableSha(object map[string]any, key string, path string) (*string, error) {
	raw, present := object[key]
	if !present {
		return nil, dissentFail(reader.code, "%s.%s is required", path, key)
	}
	if raw == nil {
		return nil, nil
	}
	value, ok := raw.(string)
	if !ok || !dissentSha256Pattern.MatchString(value) {
		return nil, dissentFail(reader.code, "%s.%s must be a sha256 hex or null", path, key)
	}
	return &value, nil
}

func (reader dissentReader) sha(object map[string]any, key string, path string, pattern *regexp.Regexp) (string, error) {
	value, err := reader.str(object, key, path, 0, 0)
	if err != nil {
		return "", err
	}
	if !pattern.MatchString(value) {
		return "", dissentFail(reader.code, "%s.%s is not a valid digest", path, key)
	}
	return value, nil
}

func (reader dissentReader) strings(object map[string]any, key string, path string, min int, max int, itemMin int, itemMax int) ([]string, error) {
	raw, present := object[key]
	if !present {
		return nil, dissentFail(reader.code, "%s.%s is required", path, key)
	}
	items, ok := raw.([]any)
	if !ok {
		return nil, dissentFail(reader.code, "%s.%s must be an array", path, key)
	}
	if len(items) < min || (max > 0 && len(items) > max) {
		return nil, dissentFail(reader.code, "%s.%s has %d items, outside [%d,%d]", path, key, len(items), min, max)
	}
	out := make([]string, 0, len(items))
	for index, item := range items {
		value, ok := item.(string)
		if !ok {
			return nil, dissentFail(reader.code, "%s.%s[%d] must be a string", path, key, index)
		}
		length := dissentStringLength(value)
		if length < itemMin || (itemMax > 0 && length > itemMax) {
			return nil, dissentFail(reader.code, "%s.%s[%d] length is outside [%d,%d]", path, key, index, itemMin, itemMax)
		}
		out = append(out, value)
	}
	return out, nil
}

func (reader dissentReader) enums(object map[string]any, key string, path string, options []string, min int, max int, unique bool) ([]string, error) {
	values, err := reader.strings(object, key, path, min, max, 0, 0)
	if err != nil {
		return nil, err
	}
	seen := map[string]bool{}
	for _, value := range values {
		if !dissentContains(options, value) {
			return nil, dissentFail(reader.code, "%s.%s contains %q, not one of %v", path, key, value, options)
		}
		if unique && seen[value] {
			return nil, dissentFail(reader.code, "%s.%s must be unique", path, key)
		}
		seen[value] = true
	}
	return values, nil
}

func dissentContains(values []string, target string) bool {
	for _, value := range values {
		if value == target {
			return true
		}
	}
	return false
}

// ---------------------------------------------------------------------------
// Parsers (workContractSchema, registries, runtime authority, plan)
// ---------------------------------------------------------------------------

func dissentParseConsequences(reader dissentReader, raw any, present bool, path string) (dissentConsequenceFacts, error) {
	facts := dissentConsequenceFacts{}
	if !present {
		return facts, nil // .default({all null})
	}
	object, err := reader.object(raw, path, dissentConsequenceNames...)
	if err != nil {
		return facts, err
	}
	for _, name := range dissentConsequenceNames {
		value, err := reader.nullableBool(object, name, path, false)
		if err != nil {
			return facts, err
		}
		facts.set(name, value)
	}
	return facts, nil
}

// dissentParseWorkContract is workContractSchema.parse.
func dissentParseWorkContract(raw any) (dissentWorkContract, error) {
	reader := dissentReader{code: dissentErrContractInvalid}
	contract := dissentWorkContract{}
	object, err := reader.object(raw, "contract", "version", "objective", "context", "acceptanceCriteria", "output", "risk", "consequences",
		"reversible", "humanReviewRequired", "assurance", "quality", "modality", "interaction", "tools", "sideEffects", "dataPolicy", "latency", "metadata")
	if err != nil {
		return contract, err
	}
	if contract.Version, err = reader.literal(object, "version", "contract", dissentWorkContractVersion); err != nil {
		return contract, err
	}
	if contract.Objective, err = reader.str(object, "objective", "contract", 3, 10_000); err != nil {
		return contract, err
	}
	if contract.Context, err = reader.str(object, "context", "contract", 1, 200_000); err != nil {
		return contract, err
	}
	if contract.AcceptanceCriteria, err = reader.strings(object, "acceptanceCriteria", "contract", 1, 30, 1, 2_000); err != nil {
		return contract, err
	}
	output, err := reader.object(object["output"], "contract.output", "format", "instructions")
	if err != nil {
		return contract, err
	}
	if contract.OutputFormat, err = reader.enum(output, "format", "contract.output", dissentOutputFormats, ""); err != nil {
		return contract, err
	}
	if contract.OutputInstructions, err = reader.str(output, "instructions", "contract.output", 1, 4_000); err != nil {
		return contract, err
	}
	if contract.Risk, err = reader.enum(object, "risk", "contract", dissentRiskLevels, "standard"); err != nil {
		return contract, err
	}
	rawConsequences, present := object["consequences"]
	if contract.Consequences, err = dissentParseConsequences(reader, rawConsequences, present, "contract.consequences"); err != nil {
		return contract, err
	}
	if contract.Reversible, err = reader.nullableBool(object, "reversible", "contract", true); err != nil {
		return contract, err
	}
	falseDefault := false
	if contract.HumanReviewRequired, err = reader.boolean(object, "humanReviewRequired", "contract", &falseDefault); err != nil {
		return contract, err
	}
	if contract.Assurance, err = reader.enum(object, "assurance", "contract", []string{"auto", "required"}, "auto"); err != nil {
		return contract, err
	}
	if contract.Quality, err = reader.enum(object, "quality", "contract", dissentQualities, "balanced"); err != nil {
		return contract, err
	}
	if contract.Modality, err = reader.literal(object, "modality", "contract", "text"); err != nil {
		return contract, err
	}
	if contract.Interaction, err = reader.literal(object, "interaction", "contract", "asynchronous"); err != nil {
		return contract, err
	}
	if contract.Tools, err = reader.literal(object, "tools", "contract", "none"); err != nil {
		return contract, err
	}
	if contract.SideEffects, err = reader.literal(object, "sideEffects", "contract", "none"); err != nil {
		return contract, err
	}
	dataPolicy, err := reader.object(object["dataPolicy"], "contract.dataPolicy", "classification", "providerStorage", "contextRetention")
	if err != nil {
		return contract, err
	}
	if contract.DataClassification, err = reader.enum(dataPolicy, "classification", "contract.dataPolicy", dissentClassification, ""); err != nil {
		return contract, err
	}
	if contract.ProviderStorage, err = reader.literal(dataPolicy, "providerStorage", "contract.dataPolicy", "forbidden"); err != nil {
		return contract, err
	}
	if contract.ContextRetention, err = reader.literal(dataPolicy, "contextRetention", "contract.dataPolicy", "request_only"); err != nil {
		return contract, err
	}
	latency, err := reader.object(object["latency"], "contract.latency", "endToEndDeadlineMs")
	if err != nil {
		return contract, err
	}
	if contract.EndToEndDeadlineMs, err = reader.integer(latency, "endToEndDeadlineMs", "contract.latency", 1_000, 3_600_000); err != nil {
		return contract, err
	}
	contract.Metadata = map[string]string{}
	if rawMetadata, present := object["metadata"]; present {
		metadata, ok := rawMetadata.(map[string]any)
		if !ok {
			return contract, dissentFail(reader.code, "contract.metadata must be a string record")
		}
		for key, item := range metadata {
			value, ok := item.(string)
			if !ok || dissentStringLength(value) > 2_000 {
				return contract, dissentFail(reader.code, "contract.metadata[%q] must be a string of at most 2000 characters", key)
			}
			contract.Metadata[key] = value
		}
	}
	return contract, nil
}

func dissentParseProfile(reader dissentReader, raw any, path string) (dissentExecutionProfile, error) {
	profile := dissentExecutionProfile{}
	object, err := reader.object(raw, path, "provider", "model", "reasoningEffort", "timeoutMs", "maxOutputTokens")
	if err != nil {
		return profile, err
	}
	if profile.Provider, err = reader.enum(object, "provider", path, dissentProviders, ""); err != nil {
		return profile, err
	}
	if profile.Model, err = reader.str(object, "model", path, 1, 0); err != nil {
		return profile, err
	}
	if profile.ReasoningEffort, err = reader.enum(object, "reasoningEffort", path, dissentReasoningEfforts, ""); err != nil {
		return profile, err
	}
	if profile.TimeoutMs, err = reader.integer(object, "timeoutMs", path, 1, math.MaxFloat64); err != nil {
		return profile, err
	}
	if profile.MaxOutputTokens, err = reader.integer(object, "maxOutputTokens", path, 1, math.MaxFloat64); err != nil {
		return profile, err
	}
	return profile, nil
}

// dissentExecutionProfileID is executionProfileId(profile).
func dissentExecutionProfileID(profile dissentExecutionProfile) (string, error) {
	canonical, err := dissentCanonicalJSON(profile.canonical())
	if err != nil {
		return "", err
	}
	return dissentSha256Hex(canonical), nil
}

func dissentParseExecutorRoute(reader dissentReader, raw any, path string) (dissentExecutorRoute, error) {
	route := dissentExecutorRoute{}
	object, err := reader.object(raw, path, "profile", "profileId", "qualifiedWorkClasses", "eligibleQualities", "qualificationReportSha256")
	if err != nil {
		return route, err
	}
	if route.Profile, err = dissentParseProfile(reader, object["profile"], path+".profile"); err != nil {
		return route, err
	}
	if route.ProfileID, err = reader.sha(object, "profileId", path, dissentSha256Pattern); err != nil {
		return route, err
	}
	if route.QualifiedWorkClasses, err = reader.enums(object, "qualifiedWorkClasses", path, dissentWorkClasses, 1, 0, true); err != nil {
		return route, err
	}
	if route.EligibleQualities, err = reader.enums(object, "eligibleQualities", path, dissentQualities, 1, 0, true); err != nil {
		return route, err
	}
	if route.QualificationReportSha256, err = reader.sha(object, "qualificationReportSha256", path, dissentSha256Pattern); err != nil {
		return route, err
	}
	expected, err := dissentExecutionProfileID(route.Profile)
	if err != nil {
		return route, dissentFail(reader.code, "%s.profile canonicalization: %v", path, err)
	}
	if route.ProfileID != expected {
		return route, dissentFail(reader.code, "%s.profileId: Executor profile identity does not match its runtime profile", path)
	}
	return route, nil
}

// dissentParseExecutorRegistry is executorQualificationRegistrySchema.parse.
func dissentParseExecutorRegistry(raw any) (dissentExecutorRegistry, error) {
	reader := dissentReader{code: dissentErrRegistryInvalid}
	registry := dissentExecutorRegistry{raw: raw, Routes: map[string][]dissentExecutorRoute{}}
	object, err := reader.object(raw, "registry", "version", "productionEligible", "sourceReportSha256", "routes")
	if err != nil {
		return registry, err
	}
	if registry.Version, err = reader.str(object, "version", "registry", 1, 0); err != nil {
		return registry, err
	}
	if registry.ProductionEligible, err = reader.boolean(object, "productionEligible", "registry", nil); err != nil {
		return registry, err
	}
	if registry.SourceReportSha256, err = reader.nullableSha(object, "sourceReportSha256", "registry"); err != nil {
		return registry, err
	}
	routes, err := reader.object(object["routes"], "registry.routes", dissentWorkClasses...)
	if err != nil {
		return registry, err
	}
	for _, workClass := range dissentWorkClasses {
		raw, present := routes[workClass]
		if !present {
			return registry, dissentFail(reader.code, "registry.routes.%s is required", workClass)
		}
		items, ok := raw.([]any)
		if !ok {
			return registry, dissentFail(reader.code, "registry.routes.%s must be an array", workClass)
		}
		parsed := make([]dissentExecutorRoute, 0, len(items))
		for index, item := range items {
			route, err := dissentParseExecutorRoute(reader, item, fmt.Sprintf("registry.routes.%s[%d]", workClass, index))
			if err != nil {
				return registry, err
			}
			if !dissentContains(route.QualifiedWorkClasses, workClass) {
				return registry, dissentFail(reader.code, "registry.routes.%s[%d].qualifiedWorkClasses: A route must be qualified for the registry class where it is published", workClass, index)
			}
			parsed = append(parsed, route)
		}
		registry.Routes[workClass] = parsed
	}
	return registry, nil
}

func dissentParseAssuranceSeats(reader dissentReader, raw any, path string) ([]dissentAssuranceSeat, error) {
	items, ok := raw.([]any)
	if !ok {
		return nil, dissentFail(reader.code, "%s must be an array", path)
	}
	seats := make([]dissentAssuranceSeat, 0, len(items))
	for index, item := range items {
		seatPath := fmt.Sprintf("%s[%d]", path, index)
		object, err := reader.object(item, seatPath, "profile", "profileId", "qualificationReportSha256")
		if err != nil {
			return nil, err
		}
		seat := dissentAssuranceSeat{}
		if seat.Profile, err = dissentParseProfile(reader, object["profile"], seatPath+".profile"); err != nil {
			return nil, err
		}
		if seat.ProfileID, err = reader.sha(object, "profileId", seatPath, dissentAssuranceProfileIDPattern); err != nil {
			return nil, err
		}
		if seat.QualificationReportSha256, err = reader.sha(object, "qualificationReportSha256", seatPath, dissentSha256Pattern); err != nil {
			return nil, err
		}
		seats = append(seats, seat)
	}
	return seats, nil
}

func dissentParseAssuranceRegistry(reader dissentReader, raw any, path string) (dissentAssuranceRegistry, error) {
	registry := dissentAssuranceRegistry{raw: raw, Coverage: map[string]dissentAssuranceCoverage{}}
	object, err := reader.object(raw, path, "version", "productionEligible", "sourceReportSha256", "coverage")
	if err != nil {
		return registry, err
	}
	if registry.Version, err = reader.str(object, "version", path, 1, 0); err != nil {
		return registry, err
	}
	if registry.ProductionEligible, err = reader.boolean(object, "productionEligible", path, nil); err != nil {
		return registry, err
	}
	if registry.SourceReportSha256, err = reader.nullableSha(object, "sourceReportSha256", path); err != nil {
		return registry, err
	}
	coverage, err := reader.object(object["coverage"], path+".coverage", dissentWorkClasses...)
	if err != nil {
		return registry, err
	}
	for _, workClass := range dissentWorkClasses {
		classPath := path + ".coverage." + workClass
		raw, present := coverage[workClass]
		if !present {
			return registry, dissentFail(reader.code, "%s is required", classPath)
		}
		roles, err := reader.object(raw, classPath, "reviewer", "challenger", "judge")
		if err != nil {
			return registry, err
		}
		entry := dissentAssuranceCoverage{}
		for role, target := range map[string]*[]dissentAssuranceSeat{"reviewer": &entry.Reviewer, "challenger": &entry.Challenger, "judge": &entry.Judge} {
			rawSeats, present := roles[role]
			if !present {
				return registry, dissentFail(reader.code, "%s.%s is required", classPath, role)
			}
			seats, err := dissentParseAssuranceSeats(reader, rawSeats, classPath+"."+role)
			if err != nil {
				return registry, err
			}
			*target = seats
		}
		registry.Coverage[workClass] = entry
	}
	return registry, nil
}

// dissentParseRuntimeAuthority is coordinationRuntimeAuthoritySchema.parse.
func dissentParseRuntimeAuthority(raw any) (dissentRuntimeAuthority, error) {
	reader := dissentReader{code: dissentErrRuntimeInvalid}
	runtime := dissentRuntimeAuthority{}
	object, err := reader.object(raw, "runtime", "tenantPolicy", "availableProviders", "assuranceRegistry")
	if err != nil {
		return runtime, err
	}
	policy, err := reader.object(object["tenantPolicy"], "runtime.tenantPolicy", "version", "authenticated", "sourceSha256", "allowedProviders")
	if err != nil {
		return runtime, err
	}
	runtime.TenantPolicy.raw = object["tenantPolicy"]
	if runtime.TenantPolicy.Version, err = reader.str(policy, "version", "runtime.tenantPolicy", 1, 0); err != nil {
		return runtime, err
	}
	if runtime.TenantPolicy.Authenticated, err = reader.boolean(policy, "authenticated", "runtime.tenantPolicy", nil); err != nil {
		return runtime, err
	}
	if runtime.TenantPolicy.SourceSha256, err = reader.nullableSha(policy, "sourceSha256", "runtime.tenantPolicy"); err != nil {
		return runtime, err
	}
	if runtime.TenantPolicy.AllowedProviders, err = reader.enums(policy, "allowedProviders", "runtime.tenantPolicy", dissentProviders, 1, 3, true); err != nil {
		return runtime, err
	}
	if runtime.AvailableProviders, err = reader.enums(object, "availableProviders", "runtime", dissentProviders, 0, 3, true); err != nil {
		return runtime, err
	}
	if runtime.AssuranceRegistry, err = dissentParseAssuranceRegistry(reader, object["assuranceRegistry"], "runtime.assuranceRegistry"); err != nil {
		return runtime, err
	}
	return runtime, nil
}

// ---------------------------------------------------------------------------
// assurance.ts — classifier + risk escalation
// ---------------------------------------------------------------------------

var (
	dissentSecurityPattern    = regexp.MustCompile(`\b(auth(?:entication|orization)?|tenant|idor|injection|xss|csrf|secret|permission|privilege|security|vulnerab|exploit|threat)\b`)
	dissentReliabilityPattern = regexp.MustCompile(`\b(concurren|race|timeout|retry|idempoten|rollback|recovery|reconcile|outage|failure|atomic|transaction|distributed|reliab|queue|crash)\b`)
	dissentResearchPattern    = regexp.MustCompile(`\b(research|source|citation|factual|fact-check|evidence quality|freshness|claim)\b`)
	dissentDocumentPattern    = regexp.MustCompile(`\b(contract|agreement|policy|terms|clause|compliance|requirement document)\b`)
	dissentBusinessPattern    = regexp.MustCompile(`\b(strategy|decision|option|tradeoff|market|pricing|business|investment|recommendation)\b`)
)

func dissentRiskRank(risk string) int {
	switch risk {
	case "critical":
		return 3
	case "high":
		return 2
	}
	return 1
}

func dissentMaxRisk(a, b string) string {
	if dissentRiskRank(a) >= dissentRiskRank(b) {
		return a
	}
	return b
}

// dissentClassifyWorkClasses is classifyWorkClasses(input).
func dissentClassifyWorkClasses(input dissentCheckInput) []string {
	corpus := dissentToLowerJS(input.Objective + "\n" + strings.Join(input.AcceptanceCriteria, "\n") + "\n" + input.ArtifactContent)
	classes := map[string]bool{}
	if dissentSecurityPattern.MatchString(corpus) {
		classes["software_security"] = true
	}
	if dissentReliabilityPattern.MatchString(corpus) {
		classes["software_reliability"] = true
	}
	if dissentResearchPattern.MatchString(corpus) {
		classes["research_factuality"] = true
	}
	if dissentDocumentPattern.MatchString(corpus) {
		classes["document_contract"] = true
	}
	if dissentBusinessPattern.MatchString(corpus) {
		classes["business_decision"] = true
	}
	switch input.ArtifactKind {
	case "code_diff":
		classes["software_correctness"] = true
	case "document":
		classes["document_contract"] = true
	case "decision":
		classes["business_decision"] = true
	case "analysis":
		classes["research_factuality"] = true
	}
	facts := input.Consequences
	if facts.isTrue("customerData") || facts.isTrue("moneyMovement") {
		classes["software_security"] = true
	}
	if facts.isTrue("moneyMovement") || facts.isTrue("irreversible") || (facts.isTrue("production") && input.ArtifactKind == "code_diff") {
		classes["software_reliability"] = true
	}
	if facts.isTrue("irreversible") {
		classes["business_decision"] = true
	}
	if facts.isTrue("regulated") {
		classes["research_factuality"] = true
		classes["document_contract"] = true
	}
	if len(classes) == 0 {
		classes["general"] = true
	}
	ordered := make([]string, 0, len(classes))
	for _, workClass := range dissentWorkClassPriority {
		if classes[workClass] {
			ordered = append(ordered, workClass)
		}
	}
	return ordered
}

// dissentClassifyAssurance is classifyAssurance(input).
func dissentClassifyAssurance(input dissentCheckInput) dissentAssuranceClassification {
	workClasses := dissentClassifyWorkClasses(input)
	reasons := []string{}
	serverRisk := "standard"
	facts := input.Consequences
	unknown, trueFacts := []string{}, []string{}
	for _, name := range dissentConsequenceNames {
		switch value := facts.get(name); {
		case value == nil:
			unknown = append(unknown, name)
		case *value:
			trueFacts = append(trueFacts, name)
		}
	}
	if len(unknown) > 0 {
		serverRisk = "high"
		reasons = append(reasons, "unknown_consequences:"+strings.Join(unknown, ","))
	}
	if len(trueFacts) > 0 {
		serverRisk = "high"
		reasons = append(reasons, "material_consequences:"+strings.Join(trueFacts, ","))
	}
	if (facts.isTrue("production") && facts.isTrue("moneyMovement")) || (facts.isTrue("production") && facts.isTrue("irreversible")) ||
		(facts.isTrue("production") && facts.isTrue("regulated") && facts.isTrue("customerData")) {
		serverRisk = "critical"
		reasons = append(reasons, "critical_consequence_combination")
	}
	if dissentContains(workClasses, "software_security") && facts.isTrue("production") {
		serverRisk = "critical"
		reasons = append(reasons, "production_security_surface")
	}
	effectiveRisk := dissentMaxRisk(input.Risk, serverRisk)
	if dissentRiskRank(input.Risk) > dissentRiskRank(serverRisk) {
		reasons = append(reasons, "caller_escalation:"+input.Risk)
	}
	if len(reasons) == 0 {
		reasons = append(reasons, "explicitly_non_material_consequences")
	}
	return dissentAssuranceClassification{RequestedRisk: input.Risk, EffectiveRisk: effectiveRisk, WorkClasses: workClasses, Reasons: reasons}
}

// dissentParseCheckInput reads a DissentCheckInput (frontierCheckInputSchema
// subset the classifier consumes) from decoded JSON.
func dissentParseCheckInput(raw any) (dissentCheckInput, error) {
	reader := dissentReader{code: dissentErrContractInvalid}
	input := dissentCheckInput{}
	object, err := reader.object(raw, "input", "objective", "artifact", "acceptanceCriteria", "evidence", "risk", "consequences", "metadata")
	if err != nil {
		return input, err
	}
	if input.Objective, err = reader.str(object, "objective", "input", 3, 10_000); err != nil {
		return input, err
	}
	artifact, err := reader.object(object["artifact"], "input.artifact", "kind", "content", "primaryProvider")
	if err != nil {
		return input, err
	}
	if input.ArtifactKind, err = reader.enum(artifact, "kind", "input.artifact", dissentArtifactKinds, ""); err != nil {
		return input, err
	}
	if input.ArtifactContent, err = reader.str(artifact, "content", "input.artifact", 1, 500_000); err != nil {
		return input, err
	}
	if input.AcceptanceCriteria, err = reader.strings(object, "acceptanceCriteria", "input", 1, 30, 1, 2_000); err != nil {
		return input, err
	}
	if input.Risk, err = reader.enum(object, "risk", "input", dissentRiskLevels, "standard"); err != nil {
		return input, err
	}
	rawConsequences, present := object["consequences"]
	if input.Consequences, err = dissentParseConsequences(reader, rawConsequences, present, "input.consequences"); err != nil {
		return input, err
	}
	input.Metadata = map[string]string{}
	return input, nil
}

// ---------------------------------------------------------------------------
// coordination.ts — deriveConsequences, consequentialUnknowns, selection,
// sealing, compileIntelligencePlan
// ---------------------------------------------------------------------------

var dissentConsequenceSignals = []struct {
	name    string
	pattern *regexp.Regexp
}{
	{"production", regexp.MustCompile(`\b(prod(?:uction)?|deploy(?:ment|ing)?|live environment|customer-facing)\b`)},
	// The TS source writes \s here; RE2's \s is only [\t\n\f\r ], so the
	// class is spelled out (dissentJSWhitespace) to match ECMAScript's.
	{"customerData", regexp.MustCompile(`\b(customer|tenant|user|patient|employee)` + dissentJSWhitespace + `+(?:data|record|identity|information)|\bpii\b`)},
	{"moneyMovement", regexp.MustCompile(`\b(payment|refund|payout|transfer|trade|money movement|charge customer)\b`)},
	{"irreversible", regexp.MustCompile(`\b(irreversible|cannot be undone|permanent delete|destructive migration)\b`)},
	{"regulated", regexp.MustCompile(`\b(regulated|hipaa|pci|sox|gdpr|ferpa|compliance obligation)\b`)},
}

func dissentDeriveConsequences(contract dissentWorkContract) (dissentConsequenceFacts, []string) {
	corpus := dissentToLowerJS(contract.Objective + "\n" + contract.Context + "\n" + strings.Join(contract.AcceptanceCriteria, "\n"))
	facts := contract.Consequences
	reasons := []string{}
	for _, signal := range dissentConsequenceSignals {
		if signal.pattern.MatchString(corpus) && !facts.isTrue(signal.name) {
			yes := true
			facts.set(signal.name, &yes)
			reasons = append(reasons, "server_detected_"+signal.name)
		}
	}
	return facts, reasons
}

func dissentConsequentialUnknowns(contract dissentWorkContract) []string {
	unknowns := []string{}
	for _, name := range dissentConsequenceNames {
		if contract.Consequences.get(name) == nil {
			unknowns = append(unknowns, "Confirm whether "+name+" is involved.")
		}
	}
	if contract.Reversible == nil {
		unknowns = append(unknowns, "Confirm whether the requested work is reversible.")
	}
	return unknowns
}

func dissentTopologyReasons(contract dissentWorkContract, workClasses []string, topology string, effectiveRisk string, inferred []string) []string {
	if topology == dissentTopologyDirect {
		return []string{"Classified as " + strings.Join(workClasses, ", ") + "; no material consequence signal was detected and the work is reversible."}
	}
	triggers := []string{}
	if contract.Assurance == "required" {
		triggers = append(triggers, "assurance was explicitly required")
	}
	if effectiveRisk != "standard" {
		triggers = append(triggers, effectiveRisk+" effective risk was classified")
	}
	triggers = append(triggers, inferred...)
	if contract.Reversible != nil && !*contract.Reversible {
		triggers = append(triggers, "the work is not reversible")
	}
	if contract.HumanReviewRequired {
		triggers = append(triggers, "a human gate is required")
	}
	return []string{"Full Dissent is mandatory because " + strings.Join(triggers, "; ") + "."}
}

func dissentEmptyAssurancePlan(required bool, humanGate bool) dissentPlanAssurance {
	families := 0
	if required {
		families = 2
	}
	return dissentPlanAssurance{Required: required, RequiredIndependentFamilies: families, HumanGateAfterAssurance: humanGate, Assignments: []dissentAssuranceAssignment{}}
}

func dissentLatencyPlan(deadlineMs int, executorTimeoutMs *int, criticalPathMs int) dissentLatencyBudget {
	budget := dissentLatencyBudget{EndToEndDeadlineMs: deadlineMs, ExecutorTimeoutMs: executorTimeoutMs, AssuranceCriticalPathTimeoutMs: criticalPathMs}
	if executorTimeoutMs != nil {
		worst := *executorTimeoutMs + criticalPathMs
		budget.WorstCaseTimeoutMs = &worst
	}
	return budget
}

type dissentPlanAuthority struct {
	executorRegistry   dissentPlanRegistryRef
	tenantPolicy       dissentPlanPolicyRef
	availabilitySha256 string
}

func dissentSha256OfCanonical(value any) (string, error) {
	canonical, err := dissentCanonicalJSON(value)
	if err != nil {
		return "", err
	}
	return dissentSha256Hex(canonical), nil
}

func dissentPlanAuthorityFor(registry dissentExecutorRegistry, runtime dissentRuntimeAuthority) (dissentPlanAuthority, error) {
	registrySha, err := dissentSha256OfCanonical(registry.raw)
	if err != nil {
		return dissentPlanAuthority{}, dissentFail(dissentErrRegistryInvalid, "registry canonicalization: %v", err)
	}
	policySha, err := dissentSha256OfCanonical(runtime.TenantPolicy.raw)
	if err != nil {
		return dissentPlanAuthority{}, dissentFail(dissentErrRuntimeInvalid, "tenant policy canonicalization: %v", err)
	}
	available := append([]string(nil), runtime.AvailableProviders...)
	sort.Strings(available)
	availableAny := make([]any, 0, len(available))
	for _, provider := range available {
		availableAny = append(availableAny, provider)
	}
	availabilitySha, err := dissentSha256OfCanonical(availableAny)
	if err != nil {
		return dissentPlanAuthority{}, dissentFail(dissentErrRuntimeInvalid, "availability canonicalization: %v", err)
	}
	return dissentPlanAuthority{
		executorRegistry:   dissentPlanRegistryRef{Version: registry.Version, SourceReportSha256: registry.SourceReportSha256, RegistrySha256: registrySha},
		tenantPolicy:       dissentPlanPolicyRef{Version: runtime.TenantPolicy.Version, SourceSha256: runtime.TenantPolicy.SourceSha256, PolicySha256: policySha},
		availabilitySha256: availabilitySha,
	}, nil
}

func dissentPlanSeatFromProfile(profile dissentExecutionProfile, profileID string, reportSha string) dissentPlanSeat {
	return dissentPlanSeat{
		Provider: profile.Provider, Model: profile.Model, ReasoningEffort: profile.ReasoningEffort,
		TimeoutMs: profile.TimeoutMs, MaxOutputTokens: profile.MaxOutputTokens, ProfileID: profileID, QualificationReportSha256: reportSha,
	}
}

// dissentSelectExecutor is selectExecutor: the first route published under
// the primary class that the policy allows, that is eligible for the quality,
// fits the deadline, and is qualified for EXACTLY the detected class set with
// every class publishing the same profile.
func dissentSelectExecutor(registry dissentExecutorRegistry, workClasses []string, quality string, deadlineMs int, allowed map[string]bool) *dissentExecutorRoute {
	for _, candidate := range registry.Routes[workClasses[0]] {
		if !allowed[candidate.Profile.Provider] || !dissentContains(candidate.EligibleQualities, quality) || candidate.Profile.TimeoutMs > deadlineMs {
			continue
		}
		if len(candidate.QualifiedWorkClasses) != len(workClasses) {
			continue
		}
		covered := true
		for _, workClass := range workClasses {
			published := false
			for _, route := range registry.Routes[workClass] {
				if route.ProfileID == candidate.ProfileID {
					published = true
					break
				}
			}
			if !dissentContains(candidate.QualifiedWorkClasses, workClass) || !published {
				covered = false
				break
			}
		}
		if covered {
			route := candidate
			return &route
		}
	}
	return nil
}

func dissentHasQualifiedProfile(registry dissentExecutorRegistry, workClasses []string, quality string, deadlineMs int) bool {
	for _, candidate := range registry.Routes[workClasses[0]] {
		exact := true
		for _, workClass := range candidate.QualifiedWorkClasses {
			if !dissentContains(workClasses, workClass) {
				exact = false
			}
		}
		for _, workClass := range workClasses {
			if !dissentContains(candidate.QualifiedWorkClasses, workClass) {
				exact = false
			}
		}
		if exact && dissentContains(candidate.EligibleQualities, quality) && candidate.Profile.TimeoutMs <= deadlineMs {
			return true
		}
	}
	return false
}

func dissentSeatByProvider(seats []dissentAssuranceSeat, provider string) (dissentAssuranceSeat, bool) {
	for _, seat := range seats {
		if seat.Profile.Provider == provider {
			return seat, true
		}
	}
	return dissentAssuranceSeat{}, false
}

// dissentSelectAssurance is selectAssurance: for every work class, at least two
// non-maker, policy-allowed provider families with reviewer + challenger +
// judge seats; the critical path (max reviewer + max challenger + max judge
// timeout) must fit the remaining deadline. nil when Full Dissent cannot be
// staffed.
func dissentSelectAssurance(registry dissentAssuranceRegistry, workClasses []string, executor string, allowed map[string]bool, humanGate bool, availableDeadlineMs int) (*dissentPlanAssurance, int, error) {
	if !registry.ProductionEligible || registry.SourceReportSha256 == nil {
		return nil, 0, nil
	}
	assignments := []dissentAssuranceAssignment{}
	for _, workClass := range workClasses {
		coverage := registry.Coverage[workClass]
		independent := []string{}
		seen := map[string]bool{}
		for _, seat := range coverage.Reviewer {
			provider := seat.Profile.Provider
			if seen[provider] {
				continue
			}
			seen[provider] = true
			if provider == executor || !allowed[provider] {
				continue
			}
			if _, challenger := dissentSeatByProvider(coverage.Challenger, provider); !challenger {
				continue
			}
			if _, judge := dissentSeatByProvider(coverage.Judge, provider); !judge {
				continue
			}
			independent = append(independent, provider)
		}
		if len(independent) < 2 {
			return nil, 0, nil
		}
		for _, provider := range independent {
			reviewer, _ := dissentSeatByProvider(coverage.Reviewer, provider)
			challenger, _ := dissentSeatByProvider(coverage.Challenger, provider)
			judge, _ := dissentSeatByProvider(coverage.Judge, provider)
			assignments = append(assignments, dissentAssuranceAssignment{
				WorkClass:  workClass,
				Reviewer:   dissentPlanSeatFromProfile(reviewer.Profile, reviewer.ProfileID, reviewer.QualificationReportSha256),
				Challenger: dissentPlanSeatFromProfile(challenger.Profile, challenger.ProfileID, challenger.QualificationReportSha256),
				Judge:      dissentPlanSeatFromProfile(judge.Profile, judge.ProfileID, judge.QualificationReportSha256),
			})
		}
	}
	maxReviewer, maxChallenger, maxJudge := 0, 0, 0
	for _, assignment := range assignments {
		maxReviewer = max(maxReviewer, assignment.Reviewer.TimeoutMs)
		maxChallenger = max(maxChallenger, assignment.Challenger.TimeoutMs)
		maxJudge = max(maxJudge, assignment.Judge.TimeoutMs)
	}
	criticalPath := maxReviewer + maxChallenger + maxJudge
	if criticalPath > availableDeadlineMs {
		return nil, 0, nil
	}
	// The ASSURANCE registry is a field of the runtime authority
	// (runtime.assuranceRegistry, parsed with the runtime reader), so a byte
	// it cannot canonicalize is a runtime refusal, not an executor-registry
	// one — that is the input a caller has to go fix.
	registrySha, err := dissentSha256OfCanonical(registry.raw)
	if err != nil {
		return nil, 0, dissentFail(dissentErrRuntimeInvalid, "assurance registry canonicalization: %v", err)
	}
	maker := executor
	version := registry.Version
	return &dissentPlanAssurance{
		Required: true, ExcludedMakerProvider: &maker, RequiredIndependentFamilies: 2, HumanGateAfterAssurance: humanGate,
		RegistryVersion: &version, SourceReportSha256: registry.SourceReportSha256, RegistrySha256: &registrySha, Assignments: assignments,
	}, criticalPath, nil
}

// dissentSealPlan is sealPlan: stamp the fixed fields, take the id over the
// unsigned canonical bytes, then re-parse (the TS parseIntelligencePlan).
func dissentSealPlan(plan dissentIntelligencePlan) (dissentIntelligencePlan, error) {
	plan.Version = dissentIntelligencePlanVersion
	plan.QualificationAuthorityClass = "dissent"
	plan.HostBoundary = dissentHostBoundary{Tools: "host_owned", SideEffects: "host_owned", Memory: "host_owned", Approval: "host_owned"}
	plan.ContinuityMode = "online"
	plan.ID = ""
	if plan.WorkClasses == nil {
		plan.WorkClasses = []string{}
	}
	if plan.Reasons == nil {
		plan.Reasons = []string{}
	}
	if plan.Clarification == nil {
		plan.Clarification = []string{}
	}
	if plan.Assurance.Assignments == nil {
		plan.Assurance.Assignments = []dissentAssuranceAssignment{}
	}
	unsigned, err := dissentToGeneric(plan)
	if err != nil {
		return plan, dissentFail(dissentErrPlanInvalid, "plan encode: %v", err)
	}
	object := unsigned.(map[string]any)
	delete(object, "id")
	id, err := dissentSha256OfCanonical(object)
	if err != nil {
		return plan, dissentFail(dissentErrPlanInvalid, "plan canonicalization: %v", err)
	}
	object["id"] = id
	return dissentParseIntelligencePlan(object)
}

// dissentParseIntelligencePlan is parseIntelligencePlan: schema validation
// plus the identity check (id == sha256(canonical(plan without id))).
func dissentParseIntelligencePlan(raw any) (dissentIntelligencePlan, error) {
	reader := dissentReader{code: dissentErrPlanInvalid}
	object, err := reader.object(raw, "plan", "version", "id", "status", "contractSha256", "executorRegistry", "tenantPolicy", "availabilitySha256",
		"qualificationAuthorityClass", "workClasses", "topology", "executor", "assurance", "latencyBudget", "reasons", "clarification", "hostBoundary", "continuityMode")
	if err != nil {
		return dissentIntelligencePlan{}, err
	}
	encoded, err := json.Marshal(object)
	if err != nil {
		return dissentIntelligencePlan{}, dissentFail(reader.code, "plan encode: %v", err)
	}
	var plan dissentIntelligencePlan
	decoder := json.NewDecoder(strings.NewReader(string(encoded)))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&plan); err != nil {
		return dissentIntelligencePlan{}, dissentFail(reader.code, "plan shape: %v", err)
	}
	if plan.Version != dissentIntelligencePlanVersion || !dissentSha256Pattern.MatchString(plan.ID) || !dissentSha256Pattern.MatchString(plan.ContractSha256) ||
		!dissentContains([]string{dissentStatusReady, dissentStatusClarificationRequired, dissentStatusQualificationRequired, dissentStatusPolicyBlocked}, plan.Status) ||
		!dissentSha256Pattern.MatchString(plan.ExecutorRegistry.RegistrySha256) || !dissentSha256Pattern.MatchString(plan.TenantPolicy.PolicySha256) ||
		!dissentSha256Pattern.MatchString(plan.AvailabilitySha256) || plan.QualificationAuthorityClass != "dissent" || len(plan.WorkClasses) == 0 ||
		len(plan.Reasons) == 0 || plan.ContinuityMode != "online" ||
		plan.HostBoundary != (dissentHostBoundary{Tools: "host_owned", SideEffects: "host_owned", Memory: "host_owned", Approval: "host_owned"}) {
		return dissentIntelligencePlan{}, dissentFail(reader.code, "plan fields are outside the intelligencePlanSchema")
	}
	for _, workClass := range plan.WorkClasses {
		if !dissentContains(dissentWorkClasses, workClass) {
			return dissentIntelligencePlan{}, dissentFail(reader.code, "plan.workClasses contains %q", workClass)
		}
	}
	if plan.Topology != nil && *plan.Topology != dissentTopologyDirect && *plan.Topology != dissentTopologyFullDissent {
		return dissentIntelligencePlan{}, dissentFail(reader.code, "plan.topology is invalid")
	}
	if plan.Executor != nil {
		if !dissentContains(dissentProviders, plan.Executor.Provider) || plan.Executor.Model == "" || !dissentContains(dissentReasoningEfforts, plan.Executor.ReasoningEffort) ||
			plan.Executor.TimeoutMs <= 0 || plan.Executor.MaxOutputTokens <= 0 || !dissentSha256Pattern.MatchString(plan.Executor.ProfileID) || !dissentSha256Pattern.MatchString(plan.Executor.QualificationReportSha256) {
			return dissentIntelligencePlan{}, dissentFail(reader.code, "plan.executor is invalid")
		}
	}
	if plan.Assurance.RequiredIndependentFamilies < 0 || plan.Assurance.RequiredIndependentFamilies > 3 {
		return dissentIntelligencePlan{}, dissentFail(reader.code, "plan.assurance.requiredIndependentFamilies is invalid")
	}
	// providerNameSchema.nullable() / SHA256_SCHEMA.nullable(): the plan id is
	// an unkeyed hash, so a forger can always make a plan self-consistent —
	// these are the checks that keep parseIntelligencePlan a real validation
	// boundary rather than a shape cast.
	if plan.Assurance.ExcludedMakerProvider != nil && !dissentContains(dissentProviders, *plan.Assurance.ExcludedMakerProvider) {
		return dissentIntelligencePlan{}, dissentFail(reader.code, "plan.assurance.excludedMakerProvider is not a known provider")
	}
	for label, digest := range map[string]*string{
		"executorRegistry.sourceReportSha256": plan.ExecutorRegistry.SourceReportSha256,
		"tenantPolicy.sourceSha256":           plan.TenantPolicy.SourceSha256,
		"assurance.sourceReportSha256":        plan.Assurance.SourceReportSha256,
		"assurance.registrySha256":            plan.Assurance.RegistrySha256,
	} {
		if digest != nil && !dissentSha256Pattern.MatchString(*digest) {
			return dissentIntelligencePlan{}, dissentFail(reader.code, "plan.%s must be a sha256 hex or null", label)
		}
	}
	for _, assignment := range plan.Assurance.Assignments {
		if !dissentContains(dissentWorkClasses, assignment.WorkClass) {
			return dissentIntelligencePlan{}, dissentFail(reader.code, "plan.assurance.assignments contains an invalid work class")
		}
		for _, seat := range []dissentPlanSeat{assignment.Reviewer, assignment.Challenger, assignment.Judge} {
			if !dissentContains(dissentProviders, seat.Provider) || seat.Model == "" || !dissentContains(dissentReasoningEfforts, seat.ReasoningEffort) || seat.TimeoutMs <= 0 || seat.MaxOutputTokens <= 0 ||
				!dissentAssuranceProfileIDPattern.MatchString(seat.ProfileID) || !dissentSha256Pattern.MatchString(seat.QualificationReportSha256) {
				return dissentIntelligencePlan{}, dissentFail(reader.code, "plan.assurance.assignments seat is invalid")
			}
		}
	}
	if plan.LatencyBudget.EndToEndDeadlineMs <= 0 || plan.LatencyBudget.AssuranceCriticalPathTimeoutMs < 0 ||
		(plan.LatencyBudget.ExecutorTimeoutMs != nil && *plan.LatencyBudget.ExecutorTimeoutMs <= 0) || (plan.LatencyBudget.WorstCaseTimeoutMs != nil && *plan.LatencyBudget.WorstCaseTimeoutMs <= 0) {
		return dissentIntelligencePlan{}, dissentFail(reader.code, "plan.latencyBudget is invalid")
	}
	for _, reason := range append(append([]string{}, plan.Reasons...), plan.Clarification...) {
		if length := dissentStringLength(reason); length < 1 || length > 500 {
			return dissentIntelligencePlan{}, dissentFail(reader.code, "plan reason/clarification length is outside [1,500]")
		}
	}
	// Identity: the id must equal the sha256 of the canonical plan without it.
	unsigned := map[string]any{}
	for key, value := range object {
		if key != "id" {
			unsigned[key] = value
		}
	}
	expected, err := dissentSha256OfCanonical(unsigned)
	if err != nil {
		return dissentIntelligencePlan{}, dissentFail(reader.code, "plan canonicalization: %v", err)
	}
	if expected != plan.ID {
		return dissentIntelligencePlan{}, dissentFail(dissentErrPlanIdentityMismatch, "Intelligence plan identity does not match its contents")
	}
	if plan.WorkClasses == nil {
		plan.WorkClasses = []string{}
	}
	if plan.Reasons == nil {
		plan.Reasons = []string{}
	}
	if plan.Clarification == nil {
		plan.Clarification = []string{}
	}
	if plan.Assurance.Assignments == nil {
		plan.Assurance.Assignments = []dissentAssuranceAssignment{}
	}
	return plan, nil
}

// dissentCompileIntelligencePlan is compileIntelligencePlan(contract,
// registry, runtime) over decoded JSON inputs.
func dissentCompileIntelligencePlan(rawContract any, rawRegistry any, rawRuntime any) (dissentIntelligencePlan, error) {
	contract, err := dissentParseWorkContract(rawContract)
	if err != nil {
		return dissentIntelligencePlan{}, err
	}
	registry, err := dissentParseExecutorRegistry(rawRegistry)
	if err != nil {
		return dissentIntelligencePlan{}, err
	}
	runtime, err := dissentParseRuntimeAuthority(rawRuntime)
	if err != nil {
		return dissentIntelligencePlan{}, err
	}
	contractSha, err := dissentSha256OfCanonical(contract.canonical())
	if err != nil {
		return dissentIntelligencePlan{}, dissentFail(dissentErrContractInvalid, "contract canonicalization: %v", err)
	}
	inferredFacts, inferredReasons := dissentDeriveConsequences(contract)
	classification := dissentClassifyAssurance(dissentCheckInput{
		Objective: contract.Objective, ArtifactKind: "analysis", ArtifactContent: contract.Context,
		AcceptanceCriteria: contract.AcceptanceCriteria, Risk: contract.Risk, Consequences: inferredFacts, Metadata: contract.Metadata,
	})
	workClasses := classification.WorkClasses
	clarification := dissentConsequentialUnknowns(contract)
	anyTrue := false
	for _, name := range dissentConsequenceNames {
		anyTrue = anyTrue || inferredFacts.isTrue(name)
	}
	mandatory := contract.Assurance == "required" || classification.EffectiveRisk != "standard" || anyTrue ||
		(contract.Reversible != nil && !*contract.Reversible) || contract.HumanReviewRequired
	topology := dissentTopologyDirect
	if mandatory {
		topology = dissentTopologyFullDissent
	}
	authority, err := dissentPlanAuthorityFor(registry, runtime)
	if err != nil {
		return dissentIntelligencePlan{}, err
	}
	base := func(status string, required bool, reasons []string, clarification []string) dissentIntelligencePlan {
		return dissentIntelligencePlan{
			Status: status, ContractSha256: contractSha, ExecutorRegistry: authority.executorRegistry, TenantPolicy: authority.tenantPolicy,
			AvailabilitySha256: authority.availabilitySha256, WorkClasses: workClasses, Topology: nil, Executor: nil,
			Assurance:     dissentEmptyAssurancePlan(required, contract.HumanReviewRequired),
			LatencyBudget: dissentLatencyPlan(contract.EndToEndDeadlineMs, nil, 0), Reasons: reasons, Clarification: clarification,
		}
	}
	if len(clarification) > 0 {
		return dissentSealPlan(base(dissentStatusClarificationRequired, false,
			[]string{"Consequential routing inputs are incomplete; Dissent will not infer permissive defaults."}, clarification))
	}
	if !runtime.TenantPolicy.Authenticated || runtime.TenantPolicy.SourceSha256 == nil {
		return dissentSealPlan(base(dissentStatusPolicyBlocked, topology == dissentTopologyFullDissent,
			[]string{"No authenticated tenant provider policy is active for this contract."}, []string{}))
	}
	if !registry.ProductionEligible || registry.SourceReportSha256 == nil {
		return dissentSealPlan(base(dissentStatusQualificationRequired, topology == dissentTopologyFullDissent,
			[]string{"No production-qualified executor registry is active for this contract."}, []string{}))
	}
	allowed := map[string]bool{}
	for _, provider := range runtime.TenantPolicy.AllowedProviders {
		if dissentContains(runtime.AvailableProviders, provider) {
			allowed[provider] = true
		}
	}
	selected := dissentSelectExecutor(registry, workClasses, contract.Quality, contract.EndToEndDeadlineMs, allowed)
	if selected == nil {
		if dissentHasQualifiedProfile(registry, workClasses, contract.Quality, contract.EndToEndDeadlineMs) {
			return dissentSealPlan(base(dissentStatusPolicyBlocked, topology == dissentTopologyFullDissent,
				[]string{"Qualified execution exists, but authenticated policy or current availability excludes it."}, []string{}))
		}
		return dissentSealPlan(base(dissentStatusQualificationRequired, topology == dissentTopologyFullDissent,
			[]string{"No single production-qualified executor profile covers every detected work class, quality, and deadline."}, []string{}))
	}
	assurance := dissentEmptyAssurancePlan(false, contract.HumanReviewRequired)
	criticalPath := 0
	if topology == dissentTopologyFullDissent {
		selection, path, err := dissentSelectAssurance(runtime.AssuranceRegistry, workClasses, selected.Profile.Provider, allowed, contract.HumanReviewRequired,
			contract.EndToEndDeadlineMs-selected.Profile.TimeoutMs)
		if err != nil {
			return dissentIntelligencePlan{}, err
		}
		if selection == nil {
			if runtime.AssuranceRegistry.ProductionEligible {
				return dissentSealPlan(base(dissentStatusPolicyBlocked, true,
					[]string{"Authenticated policy or availability cannot supply two qualified non-maker families for every assurance role and work class."}, []string{}))
			}
			return dissentSealPlan(base(dissentStatusQualificationRequired, true,
				[]string{"No production-qualified assurance authority is active for Full Dissent."}, []string{}))
		}
		assurance, criticalPath = *selection, path
	}
	executor := dissentPlanSeatFromProfile(selected.Profile, selected.ProfileID, selected.QualificationReportSha256)
	executorTimeout := selected.Profile.TimeoutMs
	topologyValue := topology
	reasons := append(dissentTopologyReasons(contract, workClasses, topology, classification.EffectiveRisk, inferredReasons),
		fmt.Sprintf("Selected one production-qualified %s profile and assurance topology covering %s within the %d ms end-to-end deadline.",
			contract.Quality, strings.Join(workClasses, ", "), contract.EndToEndDeadlineMs))
	return dissentSealPlan(dissentIntelligencePlan{
		Status: dissentStatusReady, ContractSha256: contractSha, ExecutorRegistry: authority.executorRegistry, TenantPolicy: authority.tenantPolicy,
		AvailabilitySha256: authority.availabilitySha256, WorkClasses: workClasses, Topology: &topologyValue, Executor: &executor,
		Assurance: assurance, LatencyBudget: dissentLatencyPlan(contract.EndToEndDeadlineMs, &executorTimeout, criticalPath),
		Reasons: reasons, Clarification: []string{},
	})
}
