package main

// report_print_test.go pins the branded print document for markdown research
// reports: strict escape-first conversion (hostile markdown never becomes
// live HTML), the BonfireOS masthead/meta/footer chrome, the markdown subset
// the client reader supports (headings, pipe tables, lists, blockquotes,
// rules, links, bold, inline code), and the export trigger's routing —
// markdown enqueues the converted document as kind paper while the deck path
// stays byte-for-byte.

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// The body is model text: every span must be escaped BEFORE it gets
// structure. A <script> planted in a paragraph, heading, list item, table
// cell, bold span, code span, or link label must come out inert, and a
// javascript: URI must never become an href.
func TestResearchReportPrintHTMLEscapesHostileMarkdown(t *testing.T) {
	hostile := strings.Join([]string{
		"## Executive <script>alert('h')</script> Summary",
		"",
		"A paragraph with <script>alert('p')</script> and **bold <script>alert('b')</script>** text.",
		"",
		"- item <img src=x onerror=alert('l')>",
		"",
		"| Head <script>alert('th')</script> | Value |",
		"| --- | --- |",
		"| cell <script>alert('td')</script> | `code <script>alert('c')</script>` |",
		"",
		"> quote <script>alert('q')</script>",
		"",
		"[label <b>bold</b>](https://example.com/?q=\"><script>alert('u')</script>)",
		"[not a link](javascript:alert('js'))",
	}, "\n")

	doc := renderResearchReportPrintHTML(meetingMemoryEntry{
		ID:   "os-artifact-research-1",
		Text: hostile,
		Metadata: map[string]string{
			"title":       "Hostile <script>alert('t')</script> title",
			"requestedBy": "aj@shareability.com",
		},
	})

	// No live tag may form: every < in model text is escaped, so the raw
	// sequences can only exist if a span skipped escaping. (The onerror=
	// substring itself survives as inert TEXT inside the escaped &lt;img …
	// run — dangerous only if the tag around it forms, which is what these
	// pin.)
	if strings.Contains(doc, "<script>") || strings.Contains(doc, "<img") {
		t.Fatalf("hostile markdown leaked live HTML into the print document:\n%s", doc)
	}
	if !strings.Contains(doc, "&lt;script&gt;") {
		t.Fatal("hostile markup must survive as escaped text, not be dropped")
	}
	if strings.Contains(doc, `href="javascript:`) {
		t.Fatal("a javascript: URI must never become an href")
	}
	// The link URL's quote must be escaped inside the href attribute.
	if strings.Contains(doc, `?q="><`) {
		t.Fatalf("link href leaked an unescaped quote:\n%s", doc)
	}
	// Structure still forms around the escaped text.
	for _, want := range []string{"<h2>", "<li>", "<td>", "<blockquote>", "<strong>", "<code>"} {
		if !strings.Contains(doc, want) {
			t.Fatalf("print document lost the %s structure around escaped content", want)
		}
	}
}

// The document carries the BonfireOS brand chrome: masthead (flame mark,
// wordmark, mono kicker), title, meta line (date · requested by · worker),
// the gate-result strip and search-tag chips lifted out of the body, the
// contract sections, and the Scout colophon footer.
func TestResearchReportPrintHTMLMastheadSectionsAndFooter(t *testing.T) {
	body := strings.Join([]string{
		"**Gate result:** PASS — every dimension at or above bar.",
		"",
		"Search tags: samsung, licensing, dram",
		"",
		"## Executive Summary",
		"",
		"The short version a partner can act on.",
		"",
		"## Evidence",
		"",
		"| Company | Revenue |",
		"| --- | --- |",
		"| Samsung | $198B (FY2025) |",
		"",
		"- finding one with [a source](https://example.com/filing)",
		"1. numbered check",
		"",
		"> the strongest counter-voice",
		"",
		"---",
		"",
		"## Recommendation",
		"",
		"Do the deal.",
	}, "\n")

	created := time.Date(2026, 7, 7, 12, 0, 0, 0, time.UTC)
	doc := renderResearchReportPrintHTML(meetingMemoryEntry{
		ID:        "os-artifact-research-2",
		Text:      body,
		CreatedAt: created,
		Metadata: map[string]string{
			"title":       "Samsung licensing brief",
			"requestedBy": "aj@shareability.com",
			"model":       "claude-fable-5",
		},
	})

	for _, want := range []string{
		"BonfireOS",
		"RESEARCH BRIEF",
		"Samsung licensing brief",
		"July 7, 2026",
		"Requested by aj@shareability.com",
		"claude-fable-5",
		"Gate result",
		"PASS — every dimension at or above bar.",
		">samsung</span>",
		"<h2>Executive Summary</h2>",
		"<h2>Evidence</h2>",
		"<h2>Recommendation</h2>",
		"<th>Company</th>",
		"<td>Samsung</td>",
		"<a href=\"https://example.com/filing\">a source</a>",
		"<ol><li>numbered check</li></ol>",
		"<blockquote>the strongest counter-voice</blockquote>",
		"<hr>",
		"Generated by Scout · BonfireOS · thebonfire.xyz · July 7, 2026",
	} {
		if !strings.Contains(doc, want) {
			t.Fatalf("print document missing %q:\n%s", want, doc)
		}
	}
	// The gate line and search tags moved into the masthead: neither repeats
	// in the body flow.
	if strings.Contains(doc, "**Gate result:**") || strings.Contains(doc, "Search tags:") {
		t.Fatal("gate/search-tag preamble lines must move into the masthead, not repeat in the body")
	}
	// Self-contained print document: no external fetches of any kind.
	for _, banned := range []string{"<link", "src=\"http", "@import", "url(http"} {
		if strings.Contains(doc, banned) {
			t.Fatalf("print document must be self-contained, found %q", banned)
		}
	}
}

// The export trigger routes a markdown artifact to the paper kind with the
// converted print document as the job HTML — and the deck path is untouched:
// a deck job still carries the artifact body byte-for-byte.
func TestArtifactExportPDFMarkdownRoutesToPaperDeckUnchanged(t *testing.T) {
	_, member := shareLinkTestEnv(t)
	queueDir := setupRenderSidecarEnv(t)
	if err := writeRenderRunnerHeartbeat("test-runner"); err != nil {
		t.Fatalf("write heartbeat: %v", err)
	}

	report := seedShareArtifact(t, "draft", "## Executive Summary\n\nThe finding, with <script>alert(1)</script> inside.", nil)
	recorder := shareLinkRequest(t, http.MethodPost, "/artifacts/export-pdf", fmt.Sprintf(`{"artifactId":%q}`, report.ID), member)
	if recorder.Code != http.StatusAccepted {
		t.Fatalf("markdown export status=%d body=%s, want 202", recorder.Code, recorder.Body.String())
	}
	payload := decodeJSON(t, recorder)
	if fmt.Sprint(payload["kind"]) != renderJobKindPaper {
		t.Fatalf("markdown export kind=%v, want paper", payload["kind"])
	}
	job := readRenderJobForTest(t, queueDir, fmt.Sprint(payload["jobId"]))
	if job.Kind != renderJobKindPaper {
		t.Fatalf("queued markdown job kind=%q, want paper", job.Kind)
	}
	if !strings.Contains(job.HTML, "BonfireOS") || !strings.Contains(job.HTML, "<h2>Executive Summary</h2>") {
		t.Fatal("queued markdown job must carry the branded print document, not the raw body")
	}
	if strings.Contains(job.HTML, "<script>") {
		t.Fatal("queued print document leaked live hostile markup")
	}
	if entry, _ := kanbanApp.osArtifactByID(report.ID); entry.Metadata["renderKind"] != renderJobKindPaper {
		t.Fatalf("markdown artifact stamped renderKind=%q, want paper", entry.Metadata["renderKind"])
	}
	// A stale client naming "deck" for a markdown report is a 400, never a
	// silent rewrite.
	if recorder := shareLinkRequest(t, http.MethodPost, "/artifacts/export-pdf", fmt.Sprintf(`{"artifactId":%q,"kind":"deck"}`, report.ID), member); recorder.Code != http.StatusBadRequest {
		t.Fatalf("deck-kind export of markdown status=%d, want 400", recorder.Code)
	}

	// Deck path unchanged: the queued job HTML is the artifact body
	// byte-for-byte and the kind stays deck.
	deckBody := "<!doctype html><html><body>deck body stays verbatim</body></html>"
	deck := seedShareArtifact(t, "draft", deckBody, map[string]string{"type": "html_deck"})
	recorder = shareLinkRequest(t, http.MethodPost, "/artifacts/export-pdf", fmt.Sprintf(`{"artifactId":%q}`, deck.ID), member)
	if recorder.Code != http.StatusAccepted {
		t.Fatalf("deck export status=%d body=%s, want 202", recorder.Code, recorder.Body.String())
	}
	deckPayload := decodeJSON(t, recorder)
	deckJob := readRenderJobForTest(t, queueDir, fmt.Sprint(deckPayload["jobId"]))
	if deckJob.Kind != renderJobKindDeck {
		t.Fatalf("queued deck job kind=%q, want deck", deckJob.Kind)
	}
	if deckJob.HTML != deckBody {
		t.Fatalf("deck job HTML changed:\n got %q\nwant %q", deckJob.HTML, deckBody)
	}
}

// readRenderJobForTest decodes one queued render job file.
func readRenderJobForTest(t *testing.T, queueDir string, jobID string) renderRunnerJob {
	t.Helper()
	jobID = strings.TrimSpace(jobID)
	if jobID == "" {
		t.Fatal("export response carried no jobId")
	}
	raw, err := os.ReadFile(filepath.Join(queueDir, jobID+".json"))
	if err != nil {
		t.Fatalf("read queued job: %v", err)
	}
	var job renderRunnerJob
	if err := json.Unmarshal(raw, &job); err != nil {
		t.Fatalf("decode queued job: %v", err)
	}
	return job
}
