package main

import (
	"archive/zip"
	"bytes"
	"io"
	"strings"
	"testing"
	"time"
)

// researchReportWithReceiptForTest builds a research body carrying a valid
// provider citation receipt for two sources (one titled), the same shape
// openai_responses.go appends, plus a model-written Sources link the receipt
// never proved — the appendix must neither duplicate a proven URL nor promote
// that unproven one.
func researchReportWithReceiptForTest(t *testing.T) string {
	t.Helper()
	urls := []string{"https://example.com/filing", "https://data.example.org/mid-market"}
	digest := sha256Hex([]byte(strings.Join(urls, "\n")))
	return strings.Join([]string{
		"**Gate result:** PASS — every dimension at or above bar.",
		"",
		"Search tags: nordics, mid-market",
		"",
		"## Executive Summary",
		"",
		"The short version a partner can act on.",
		"",
		"## Evidence",
		"",
		"### Benchmarks",
		"",
		"| Company | Revenue |",
		"| --- | --- |",
		"| Samsung | $198B (FY2025) |",
		"",
		"## Sources",
		"",
		"- [Filing](https://example.com/filing)",
		"- [Only in the body](https://body.example.net/extra)",
		"",
		"## Recommendation",
		"",
		"Do the deal.",
		"",
		"## Scout source receipt",
		"- Example filing — https://example.com/filing",
		"- https://data.example.org/mid-market",
		"<!-- stride-web-citation-receipt:v1 count=2 domains=2 searches=3 response=" + sha256Hex([]byte("resp")) + " digest=" + digest + " -->",
	}, "\n")
}

// researchReportSourcesAppendixForTest slices out the appendix so provenance
// assertions cannot be satisfied (or defeated) by the report body, which
// still renders the model's own "## Sources" section, or by the inline CSS,
// which always defines the unverified badge's class.
func researchReportSourcesAppendixForTest(t *testing.T, page string) string {
	t.Helper()
	start := strings.Index(page, `<section class="sources" id="sources-appendix">`)
	if start < 0 {
		t.Fatalf("print document has no sources appendix:\n%s", page)
	}
	appendix := page[start:]
	if end := strings.Index(appendix, "</section>"); end >= 0 {
		appendix = appendix[:end]
	}
	return appendix
}

// wave11PrintContentsForTest slices the Contents nav out of a printed report
// so a test can compare the nav against the body it claims to index.
func wave11PrintContentsForTest(t *testing.T, page string) string {
	t.Helper()
	start := strings.Index(page, `<nav class="contents">`)
	if start < 0 {
		t.Fatalf("print document has no contents nav:\n%s", page)
	}
	nav := page[start:]
	if end := strings.Index(nav, "</nav>"); end >= 0 {
		nav = nav[:end]
	}
	return nav
}

func TestResearchReportPrintCarriesOrganizationBrandCoverContentsSourcesAndColophon(t *testing.T) {
	t.Setenv("STRIDE_ORGANIZATION_NAME", "Acme Ventures")
	created := time.Date(2026, 9, 2, 12, 0, 0, 0, time.UTC)
	report := meetingMemoryEntry{
		ID: "os-artifact-research-brand", Text: researchReportWithReceiptForTest(t), CreatedAt: created,
		// artifactContract is the durable research stamp: the kicker, the
		// Contents nav and the sources appendix are gated on it, so an
		// ordinary document never prints as a report
		// (TestOrdinaryDocumentPrintOmitsResearchReportChrome).
		Metadata: map[string]string{"title": "Nordic mid-market <brief>", "requestedBy": "aj@shareability.com", "model": "gpt-5.6-sol", "artifactContract": "research_brief_v2"},
	}
	doc := renderResearchReportPrintHTML(report)
	for _, want := range []string{
		`<title>Nordic mid-market &lt;brief&gt; · Acme Ventures</title>`,
		`<span class="wordmark">Acme Ventures</span>`,
		`<div class="hairline" aria-hidden="true"></div>`,
		`<span class="kicker">RESEARCH REPORT</span>`,
		`<h1 class="title">Nordic mid-market &lt;brief&gt;</h1>`,
		`<p class="prepared">Prepared for Acme Ventures</p>`,
		"September 2, 2026",
		"Requested by aj@shareability.com",
		`<nav class="contents"><h2>Contents</h2><ol>`,
		`<a href="#section-1-executive-summary">Executive Summary</a>`,
		`<li class="contents-level-3"><a href="#section-3-benchmarks">Benchmarks</a>`,
		`<section id="section-1-executive-summary"><h2>Executive Summary</h2>`,
		`<section class="sources" id="sources-appendix"><h2>Sources appendix</h2>`,
		`<li>Example filing <a href="https://example.com/filing">https://example.com/filing</a></li>`,
		`<li>https://data.example.org/mid-market <a href="https://data.example.org/mid-market">`,
		`<footer class="colophon">Prepared by Scout for Acme Ventures · September 2, 2026</footer>`,
		`.hairline{height:1.5pt;background:#ff5a19`,
	} {
		if !strings.Contains(doc, want) {
			t.Fatalf("branded print document missing %q:\n%s", want, doc)
		}
	}
	// The Stride wordmark asset never appears under another organization's name.
	for _, reject := range []string{
		"Scout source receipt", "stride-web-citation-receipt", "workinstride.xyz", "Generated by Scout", "RESEARCH BRIEF", "<brief>",
		`class="wordmark-image" role="img"`, researchReportUnverifiedSourcesNote,
	} {
		if strings.Contains(doc, reject) {
			t.Fatalf("branded print document leaked %q", reject)
		}
	}
	// The receipt is the proven set: a link the model listed under its own
	// "## Sources" heading that no receipt proved never joins the appendix,
	// and nothing in a proven appendix is badged unverified.
	appendix := researchReportSourcesAppendixForTest(t, doc)
	for _, reject := range []string{"body.example.net", "unverified"} {
		if strings.Contains(appendix, reject) {
			t.Fatalf("sources appendix leaked %q:\n%s", reject, appendix)
		}
	}
	// The appendix lists each source once even when the body repeats it.
	if strings.Count(doc, `<a href="https://example.com/filing">https://example.com/filing</a>`) != 1 {
		t.Fatal("sources appendix duplicated a receipt URL")
	}
	// Default organization when nothing is configured.
	t.Setenv("STRIDE_ORGANIZATION_NAME", "")
	if plain := renderResearchReportPrintHTML(report); !strings.Contains(plain, "Prepared by Scout for Bonfire · September 2, 2026") || !strings.Contains(plain, "Prepared for Bonfire") {
		t.Fatal("default organization name missing from the colophon/cover")
	}
	// The wordmark asset is a picture of a name: it renders only for the
	// organization it actually spells, and every other organization gets its
	// own name as the text wordmark instead of somebody else's logo.
	if _, ok := researchReportWordmarkDataURI("Acme Ventures"); ok {
		t.Fatal("the Stride wordmark asset was offered to another organization")
	}
	if _, ok := researchReportWordmarkDataURI(""); ok {
		t.Fatal("an unnamed organization was given a wordmark asset")
	}
	asset, ok := researchReportWordmarkDataURI(researchReportWordmarkBrand)
	if !ok || !strings.HasPrefix(asset, "data:image/png;base64,") {
		t.Fatal("the wordmark asset is missing for its own brand")
	}
	t.Setenv("STRIDE_ORGANIZATION_NAME", researchReportWordmarkBrand)
	branded := renderResearchReportPrintHTML(report)
	if !strings.Contains(branded, `class="wordmark-image" role="img" aria-label="`+researchReportWordmarkBrand+`" style="background-image:url(data:image/png;base64,`) {
		t.Fatalf("the wordmark asset is missing from its own brand's masthead:\n%s", branded)
	}
}

func TestResearchReportBrandedMarkdownFeedsDOCXWithTheSameRenderPass(t *testing.T) {
	t.Setenv("STRIDE_ORGANIZATION_NAME", "Acme Ventures")
	created := time.Date(2026, 9, 2, 12, 0, 0, 0, time.UTC)
	report := meetingMemoryEntry{
		ID: "os-artifact-research-docx", Text: researchReportWithReceiptForTest(t), CreatedAt: created,
		Metadata: map[string]string{"title": "Nordic mid-market", "requestedBy": "aj@shareability.com", "mode": "research", "artifactContract": "research_brief_v2"},
	}
	markdown := documentExportMarkdown(report)
	for _, want := range []string{
		"*RESEARCH REPORT*",
		"# Nordic mid-market",
		"**Prepared for Acme Ventures** · September 2, 2026 · Requested by aj@shareability.com",
		"**Gate result:** PASS",
		"Search tags: nordics, mid-market",
		"## Contents\n\n- Executive Summary\n- Evidence\n  - Benchmarks\n- Sources\n- Recommendation",
		"## Executive Summary\n\nThe short version",
		"## Sources appendix\n\n1. [Example filing](https://example.com/filing)\n2. [https://data.example.org/mid-market](https://data.example.org/mid-market)",
		"*Prepared by Scout for Acme Ventures · September 2, 2026*",
	} {
		if !strings.Contains(markdown, want) {
			t.Fatalf("branded markdown missing %q:\n%s", want, markdown)
		}
	}
	if strings.Contains(markdown, "Scout source receipt") || strings.Contains(markdown, "stride-web-citation-receipt") {
		t.Fatal("branded markdown leaked the receipt block")
	}
	// An organization that is not the wordmark asset's brand exports its own
	// name, never another brand's logo.
	if strings.Contains(markdown, "wordmark](data:image") || strings.Contains(markdown, "· unverified") {
		t.Fatalf("branded markdown carried a foreign wordmark or an unproven source:\n%s", markdown)
	}
	// The PDF pass and the DOCX pass agree on the same document facts: the
	// receipt proved two sources, and only those two are in the appendix.
	printed := researchReportBrandedDocumentFor(report)
	if len(printed.Sources) != 2 || !printed.SourcesVerified || printed.Colophon != "Prepared by Scout for Acme Ventures · September 2, 2026" || len(printed.Sections) != 5 {
		t.Fatalf("branded document=%+v", printed)
	}
	for _, source := range printed.Sources {
		if !source.Verified {
			t.Fatalf("a receipt-proven source lost its provenance: %+v", source)
		}
	}
	docx, err := compileDocumentDOCX(markdown, "Nordic mid-market", nil, nil)
	if err != nil {
		t.Fatalf("compile branded DOCX: %v", err)
	}
	reader, err := zip.NewReader(bytes.NewReader(docx), int64(len(docx)))
	if err != nil {
		t.Fatal(err)
	}
	documentXML := ""
	mediaParts := 0
	for _, file := range reader.File {
		if strings.HasPrefix(file.Name, "word/media/") {
			mediaParts++
		}
		if file.Name != "word/document.xml" {
			continue
		}
		opened, openErr := file.Open()
		if openErr != nil {
			t.Fatal(openErr)
		}
		raw, readErr := io.ReadAll(opened)
		opened.Close()
		if readErr != nil {
			t.Fatal(readErr)
		}
		documentXML = string(raw)
	}
	for _, want := range []string{"RESEARCH REPORT", "Prepared for Acme Ventures", "Contents", "Sources appendix", "Prepared by Scout for Acme Ventures", "Executive Summary"} {
		if !strings.Contains(documentXML, want) {
			t.Fatalf("DOCX document.xml missing %q", want)
		}
	}
	if mediaParts != 0 {
		t.Fatalf("DOCX embedded %d media parts for an organization with no wordmark asset", mediaParts)
	}
	// The asset's own brand still ships its wordmark into the .docx.
	t.Setenv("STRIDE_ORGANIZATION_NAME", researchReportWordmarkBrand)
	brandedDOCX, err := compileDocumentDOCX(documentExportMarkdown(report), "Nordic mid-market", nil, nil)
	if err != nil {
		t.Fatalf("compile own-brand DOCX: %v", err)
	}
	brandedReader, err := zip.NewReader(bytes.NewReader(brandedDOCX), int64(len(brandedDOCX)))
	if err != nil {
		t.Fatal(err)
	}
	brandedMedia := 0
	for _, file := range brandedReader.File {
		if strings.HasPrefix(file.Name, "word/media/") {
			brandedMedia++
		}
	}
	if brandedMedia != 1 {
		t.Fatalf("own-brand DOCX embedded %d media parts, want the wordmark only", brandedMedia)
	}
	t.Setenv("STRIDE_ORGANIZATION_NAME", "Acme Ventures")
	// Ordinary documents export their own Markdown untouched.
	plain := meetingMemoryEntry{ID: "os-artifact-doc", Text: "# Memo\n\nbody", Metadata: map[string]string{"type": artifactTypeMarkdown, "source": studioBlankSourceDocument, "mode": "document"}}
	if documentExportMarkdown(plain) != "# Memo\n\nbody" {
		t.Fatal("plain document export was rewritten")
	}
}

// TestResearchReportAppendixMarksModelListedSourcesUnverified pins the two
// provenance rules of the branded appendix, plus the fenced-code rule the
// shared section splitter owes the DOCX compiler:
//
//   - With a provider citation receipt, the receipt IS the set.
//   - Without one, the model's own "## Sources" links are still printed (the
//     export never invents or drops a source) but are labelled unverified in
//     both the PDF and the .docx, because the receipt block is stripped from
//     the exported body and the reader has no other marker.
//   - A `#` line inside a ``` fence is code, not a heading: splitting there
//     invents a Word heading and tears the fence in half.
func TestResearchReportAppendixMarksModelListedSourcesUnverified(t *testing.T) {
	t.Setenv("STRIDE_ORGANIZATION_NAME", "Acme Ventures")
	body := strings.Join([]string{
		"## Method",
		"",
		"```bash",
		"# fetch the pricing table",
		"curl https://example.com/pricing",
		"```",
		"",
		"## Sources",
		"",
		"- [Filing](https://example.com/filing)",
		"- [Invented](https://hallucination.example.net/nope)",
	}, "\n")
	report := meetingMemoryEntry{
		ID: "os-artifact-research-unverified", Text: body,
		Metadata: map[string]string{"title": "No receipt", "mode": "research", "artifactContract": "research_brief_v2"},
	}

	doc := researchReportBrandedDocumentFor(report)
	if doc.SourcesVerified || len(doc.Sources) != 2 {
		t.Fatalf("unreceipted document sources=%+v verified=%v", doc.Sources, doc.SourcesVerified)
	}
	for _, source := range doc.Sources {
		if source.Verified {
			t.Fatalf("a model-listed link claimed receipt provenance: %+v", source)
		}
	}
	titles := make([]string, 0, len(doc.Sections))
	for _, section := range doc.Sections {
		if section.Title != "" {
			titles = append(titles, section.Title)
		}
	}
	if strings.Join(titles, "|") != "Method|Sources" {
		t.Fatalf("fenced code split the report into sections %v", titles)
	}

	markdown := documentExportMarkdown(report)
	for _, want := range []string{
		"```bash\n# fetch the pricing table\ncurl https://example.com/pricing\n```",
		researchReportUnverifiedSourcesNote,
		"1. [Filing](https://example.com/filing) · unverified",
		"2. [Invented](https://hallucination.example.net/nope) · unverified",
	} {
		if !strings.Contains(markdown, want) {
			t.Fatalf("unreceipted branded markdown missing %q:\n%s", want, markdown)
		}
	}
	if strings.Contains(markdown, "## fetch the pricing table") {
		t.Fatalf("a fenced code comment became a heading:\n%s", markdown)
	}
	if _, err := compileDocumentDOCX(markdown, "No receipt", nil, nil); err != nil {
		t.Fatalf("compile unreceipted DOCX: %v", err)
	}

	// The PDF half owes the same fence rule. The splitter refuses to split
	// inside a fence, so the Contents nav lists only Method and Sources — if
	// bodyHTML still promoted the `#` comment to an <h2> the printed document
	// would visibly disagree with its own table of contents, and the ``` lines
	// would print as two paragraphs of backticks.
	printed := renderResearchReportPrintHTML(report)
	if !strings.Contains(printed, "<pre><code># fetch the pricing table\ncurl https://example.com/pricing</code></pre>") {
		t.Fatalf("the fenced block did not print as one code block:\n%s", printed)
	}
	for _, forbidden := range []string{"fetch the pricing table</h2>", "fetch the pricing table</h3>", "fetch the pricing table</h4>", "```"} {
		if strings.Contains(printed, forbidden) {
			t.Fatalf("printed report leaked %q out of its fence:\n%s", forbidden, printed)
		}
	}
	nav := wave11PrintContentsForTest(t, printed)
	if strings.Count(nav, "<li class=\"contents-level-") != 2 || !strings.Contains(nav, ">Method</a>") || !strings.Contains(nav, ">Sources</a>") {
		t.Fatalf("the Contents nav disagrees with the printed body:\n%s", nav)
	}

	printedAppendix := researchReportSourcesAppendixForTest(t, renderResearchReportPrintHTML(report))
	if !strings.Contains(printedAppendix, `<p class="sources-note">`+researchReportUnverifiedSourcesNote+`</p>`) ||
		strings.Count(printedAppendix, `<span class="sources-unverified">unverified</span>`) != 2 {
		t.Fatalf("unreceipted print appendix is not marked unverified:\n%s", printedAppendix)
	}

	// A receipted report carries no unverified marker at all.
	verified := meetingMemoryEntry{
		ID: "os-artifact-research-verified", Text: researchReportWithReceiptForTest(t),
		Metadata: map[string]string{"title": "Receipted", "mode": "research", "artifactContract": "research_brief_v2"},
	}
	verifiedDoc := researchReportBrandedDocumentFor(verified)
	if !verifiedDoc.SourcesVerified || len(verifiedDoc.Sources) != 2 {
		t.Fatalf("receipted document sources=%+v verified=%v", verifiedDoc.Sources, verifiedDoc.SourcesVerified)
	}
	verifiedAppendix := researchReportSourcesAppendixForTest(t, renderResearchReportPrintHTML(verified))
	if strings.Contains(verifiedAppendix, "unverified") || strings.Contains(verifiedAppendix, "hallucination.example.net") {
		t.Fatalf("a receipt-proven appendix was labelled unverified:\n%s", verifiedAppendix)
	}
}
